/**
 * The work template, measured against the design instead of against itself.
 *
 * `spacing.spec.ts` compares the rendered page with the site editor's canvas.
 * That is a real bug class — a one-class rule wins in one context and loses in
 * the other (ADR-0008, ADR-0011) — and it is the only thing that file claims.
 * What it cannot do, by construction, is notice that both contexts agree on the
 * wrong number. Phase 7c reported "0 divergences across 374 elements", which was
 * true, and said nothing about whether the page looked like `design-source/`.
 * It did not: the filter chips were rendering at 54px against the design's 36,
 * and every mono caps label in the chart was four pixels taller than it should
 * have been.
 *
 * So this file has a different baseline. `tests/e2e/fixtures/` holds a JSON
 * baseline generated by `composer design:baseline`, which reads the inline
 * `style` attributes out of `design-source/*.dc.html` and writes them down
 * beside the theme selector that plays the same role. Nothing in it was chosen
 * by this theme; every value is the design's own text, `var()` names and all.
 *
 * **How a value is checked.** Each entry names one element. The element's
 * computed style is read first, then a probe of the same tag is appended beside
 * it, given the design's declarations verbatim, and read too. Both are resolved
 * by one engine, in one inherited font context, at one viewport — which is what
 * makes `ch`, `em`, `clamp()` of a viewport unit and `color-mix()` comparable at
 * all, instead of being re-implemented in PHP and compared against a number that
 * would rot. Only the longhands the design's own declarations expand to are
 * compared; the CSSOM says which those are, so nothing is asserted that the
 * design did not say.
 *
 * **What is deliberately not pinned.** Four of the chart's styles — the legend,
 * the kind label, the org name and the shipped headline — are computed inside
 * the design tool and never reach the exported file, so there is no design value
 * to assert and this file does not invent one. Everything else the theme had to
 * decide for itself carries a `skip` in the baseline with the reason written
 * out. See `docs/adr/0012-design-parity-harness.md`.
 *
 * External dependencies
 */
import * as fs from 'fs';
import * as path from 'path';
import type { Page } from '@playwright/test';
import { test, expect } from '@wordpress/e2e-test-utils-playwright';

/** One element of the design, and the theme element that plays its part. */
type Entry = {
	id: string;
	viewport: string;
	selector: string;
	source: { file: string; anchor: string };
	declarations: Record< string, string >;
	skip?: Record< string, string >;
	note?: string;
};

/** The generated baseline. */
type Baseline = {
	viewports: Record< string, number >;
	entries: Entry[];
};

const BASELINE: Baseline = JSON.parse(
	fs.readFileSync(
		path.join(
			process.cwd(),
			'tests/e2e/fixtures/work-design-baseline.json'
		),
		'utf8'
	)
);

/** Logged out: the admin bar is chrome no reader sees, and it moves the page down. */
const READER = { cookies: [], origins: [] };

/** The slugs this fixture owns. Distinct from every other spec's, deliberately. */
const SLUGS = {
	page: 'parity-fixture-work',
	post: 'parity-fixture-writeup',
	role: 'parity-fixture-lab',
	ships: [ 'parity-fixture-kiveo', 'parity-fixture-ops' ],
};

/** The work page's URL, filled in by `beforeAll`. */
let workPage = '';

/** The shape of the REST fields this spec reads back. */
type Created = { id: number; link: string };

/**
 * Delete everything carrying one of this fixture's slugs, and nothing else.
 *
 * @param requestUtils The suite's REST client.
 */
async function removeFixture(
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	requestUtils: any
): Promise< void > {
	const sweep: Array< [ string, string[] ] > = [
		[ 'pages', [ SLUGS.page ] ],
		[ 'posts', [ SLUGS.post ] ],
		[ 'dp_role', [ SLUGS.role ] ],
		[ 'dp_ship', SLUGS.ships ],
	];

	for ( const [ endpoint, slugs ] of sweep ) {
		const found: Created[] = await requestUtils.rest( {
			path: `/wp/v2/${ endpoint }`,
			params: { slug: slugs.join( ',' ), per_page: 100, status: 'any' },
		} );

		for ( const item of found ) {
			await requestUtils.rest( {
				path: `/wp/v2/${ endpoint }/${ item.id }`,
				method: 'DELETE',
				params: { force: true },
			} );
		}
	}
}

/**
 * Compare one viewport's worth of entries against the page, and say what differs.
 *
 * Returns one line per divergent property, naming the design file it came from,
 * so a failure is actionable without opening anything.
 *
 * @param page    The page, already at the right width and URL.
 * @param entries The baseline entries for this viewport.
 */
async function divergences(
	page: Page,
	entries: Entry[]
): Promise< string[] > {
	return page.evaluate( ( rows: Entry[] ) => {
		const camel = ( property: string ): string =>
			property.replace( /-([a-z])/g, ( _match, letter: string ) =>
				letter.toUpperCase()
			);

		/*
		 * A transition list serialises one value per transitioned property, so
		 * adding a fourth property to a control — which the theme does on the
		 * pills, because their current state changes background as well as
		 * colour — makes every longhand in the family differ by length while
		 * saying nothing about whether the duration or the easing is the
		 * design's. The durations and curves are tokens, so `tokens.spec.ts`
		 * already holds them, and what motion has to honour is checked by
		 * `timeline.spec.ts` under `prefers-reduced-motion`.
		 */
		const IGNORED = /^(transition|animation)/;

		const found: string[] = [];

		for ( const entry of rows ) {
			const target = document.querySelector( entry.selector );

			if ( ! target ) {
				found.push(
					`${ entry.id } — the design draws this and "${ entry.selector }" matched ` +
						`nothing on the page. [${ entry.source.file }]`
				);
				continue;
			}

			const parent = target.parentElement;

			if ( ! parent ) {
				found.push(
					`${ entry.id } — "${ entry.selector }" has no parent to probe beside.`
				);
				continue;
			}

			/*
			 * The probe is the same tag, so the user-agent stylesheet applies to
			 * both, and a sibling of the target, so both inherit from the same
			 * element. It carries no class, so nothing in the theme reaches it:
			 * what it computes is the design's declarations and nothing else.
			 */
			const probe = document.createElement( target.tagName );

			for ( const [ property, value ] of Object.entries(
				entry.declarations
			) ) {
				probe.style.setProperty( property, value );
			}

			// The CSSOM expands the design's shorthands for us, which is the
			// list of longhands the design actually constrains.
			const constrained = Array.from( probe.style )
				.map( camel )
				.filter( ( property ) => ! IGNORED.test( property ) );
			const theme: Record< string, string > = {};
			const themeStyle = window.getComputedStyle( target );

			// Read before the probe is in the document, so inserting it cannot
			// move the element it is being compared against.
			for ( const property of constrained ) {
				theme[ property ] = themeStyle.getPropertyValue(
					property.replace( /[A-Z]/g, ( c ) => '-' + c.toLowerCase() )
				);
			}

			parent.appendChild( probe );

			const probeStyle = window.getComputedStyle( probe );
			const design: Record< string, string > = {};

			for ( const property of constrained ) {
				design[ property ] = probeStyle.getPropertyValue(
					property.replace( /[A-Z]/g, ( c ) => '-' + c.toLowerCase() )
				);
			}

			probe.remove();

			for ( const property of constrained ) {
				if ( entry.skip && entry.skip[ property ] ) {
					continue;
				}

				if ( design[ property ] === theme[ property ] ) {
					continue;
				}

				found.push(
					`${ entry.id } (${ entry.selector }) ${ property } — ` +
						`design: ${ design[ property ] } / theme: ${ theme[ property ] } ` +
						`[${ entry.source.file }]`
				);
			}
		}

		return found;
	}, entries );
}

/**
 * The entries measured at one of the baseline's two widths.
 *
 * @param viewport The baseline's name for it.
 */
function entriesFor( viewport: string ): Entry[] {
	return BASELINE.entries.filter( ( entry ) => entry.viewport === viewport );
}

test.describe( 'the work template against design-source/', () => {
	/*
	 * Serial, for the same reason `timeline.spec.ts` is: one fixture, one
	 * `beforeAll` per worker, and `fullyParallel` would race two workers to
	 * create the same slugs.
	 */
	test.describe.configure( { mode: 'serial' } );
	test.use( { storageState: READER } );

	test.beforeAll( async ( { requestUtils } ) => {
		await removeFixture( requestUtils );

		const writeup = await requestUtils.rest< Created >( {
			path: '/wp/v2/posts',
			method: 'POST',
			data: {
				title: 'Parity fixture — the write-up',
				slug: SLUGS.post,
				status: 'publish',
				content: 'Placeholder.',
			},
		} );

		const role = await requestUtils.rest< Created >( {
			path: '/wp/v2/dp_role',
			method: 'POST',
			data: {
				title: 'Parity fixture — Fanxie Lab',
				slug: SLUGS.role,
				status: 'publish',
				meta: {
					dp_role_title: 'CTO & founder',
					dp_start: 2016,
					dp_end: 2026.6,
					dp_range: '2016 — now',
					dp_detail:
						'The thread running under everything else, said at enough length that the paragraph wraps.',
					dp_stack: 'LARAVEL · NESTJS',
					dp_accent: 'pink',
				},
			},
		} );

		for ( const slug of SLUGS.ships ) {
			await requestUtils.rest< Created >( {
				path: '/wp/v2/dp_ship',
				method: 'POST',
				data: {
					title: `Parity fixture — ${ slug }`,
					slug,
					status: 'publish',
					meta: {
						dp_role_id: role.id,
						dp_start: 2023,
						dp_end: 2026.6,
						dp_range: '2023 — now',
						dp_headline: 'The one line above the paragraph.',
						dp_detail:
							'What it is and who it is for, at enough length that the paragraph wraps onto a second line.',
						dp_line: 'The sentence written for the card.',
						dp_bullets: [ 'One constraint.', 'Another one.' ],
						dp_ship_role: 'Everything',
						dp_stack: 'SWIFT · SWIFTUI',
						dp_artifact_label: 'SWIFTUI',
						dp_artifact: 'struct EntryList: View { }',
						dp_stat1: '0',
						dp_stat1_label: 'TRACKERS',
						dp_stat2: '—',
						dp_stat2_label: 'APPS SHIPPED',
						dp_writeup_id: writeup.id,
						dp_featured: true,
					},
				},
			} );
		}

		const created = await requestUtils.rest< Created >( {
			path: '/wp/v2/pages',
			method: 'POST',
			data: {
				title: 'Parity fixture — where I worked',
				slug: SLUGS.page,
				status: 'publish',
				template: 'dp-work',
				meta: {
					dp_lead:
						"There's no separate portfolio here. Three projects I'd show first, then every role I've held and everything that came out of each one.",
				},
			},
		} );

		workPage = created.link;
	} );

	test.afterAll( async ( { requestUtils } ) => {
		await removeFixture( requestUtils );
	} );

	test( 'the baseline is the design, and there is enough of it to mean something', () => {
		expect(
			BASELINE.entries.length,
			'The generated baseline is empty. Run: composer design:baseline'
		).toBeGreaterThan( 40 );

		expect( entriesFor( 'desktop' ).length ).toBeGreaterThan( 40 );
		expect( entriesFor( 'narrow' ).length ).toBeGreaterThan( 0 );
	} );

	test( 'bars mode matches the design it was drawn from', async ( {
		page,
	} ) => {
		await page.setViewportSize( {
			width: BASELINE.viewports.desktop,
			height: 1200,
		} );

		const url = new URL( workPage );
		url.searchParams.set( 'dp-open', 'all' );

		await page.goto( url.toString() );
		await page.locator( '.dp-tl-panel' ).first().waitFor();

		expect(
			await divergences( page, entriesFor( 'desktop' ) ),
			'Each line is one property of one element that does not have the value ' +
				'design-source/ gives it. Fix the theme, or — if the design has moved — ' +
				're-import and run `composer design:baseline`.'
		).toEqual( [] );
	} );

	/*
	 * The one thing the property sweep above cannot see.
	 *
	 * A sweep can only compare properties the design names, and the design does
	 * not name `box-sizing` on a chip. It names `min-height: var(--target-min)`,
	 * and `_ds/tokens/spacing.css` says what that is for: "WCAG 2.5.8 (AA)
	 * requires 24px minimum. 2.5.5 (AAA) asks for 44px. Primary navigation and
	 * form controls meet 44; secondary controls such as filter chips meet 36."
	 * A target size is a property of the rendered box, so it is asserted on the
	 * rendered box.
	 *
	 * The same file settles which box: "Button, IconButton and Input all resolve
	 * to --control-h-md, so they sit flush when placed side by side. They
	 * previously differed by 2px." Three controls with different padding only sit
	 * flush if the declared height is the whole box, so the design system's
	 * control sizing is border-box. Under `content-box` these chips measured 54 —
	 * taller than the 44px primary control, which inverts the hierarchy the same
	 * paragraph describes, and which is what David saw and called huge.
	 */
	test( 'the filter chips are the target size their own token is named for', async ( {
		page,
	} ) => {
		await page.setViewportSize( {
			width: BASELINE.viewports.desktop,
			height: 1200,
		} );
		await page.goto( workPage );

		const measured = await page.evaluate( () => {
			const chips = Array.from(
				document.querySelectorAll< HTMLElement >( '.dp-tl-pills a' )
			);

			// The token, resolved the same way every other value in this file
			// is: by asking the browser rather than by repeating a number.
			const probe = document.createElement( 'div' );
			probe.style.height = 'var(--target-min)';
			probe.style.position = 'absolute';
			document.body.appendChild( probe );
			const target = window.getComputedStyle( probe ).height;
			probe.remove();

			return {
				target,
				heights: chips.map(
					( chip ) => window.getComputedStyle( chip ).height
				),
				boxes: chips.map(
					( chip ) => window.getComputedStyle( chip ).boxSizing
				),
			};
		} );

		expect( measured.target ).toBe( '36px' );
		expect( measured.heights.length ).toBeGreaterThan( 3 );

		expect(
			measured.boxes,
			'The design system sizes its controls border-box; see the note above.'
		).toEqual( measured.boxes.map( () => 'border-box' ) );

		expect(
			measured.heights,
			'A chip taller than --target-min is a chip whose padding and border ' +
				'were added on top of the height its token declares.'
		).toEqual( measured.heights.map( () => measured.target ) );
	} );

	test( 'stack mode matches the design it was drawn from', async ( {
		page,
	} ) => {
		await page.setViewportSize( {
			width: BASELINE.viewports.narrow,
			height: 1200,
		} );

		const url = new URL( workPage );
		url.searchParams.set( 'dp-open', 'all' );

		await page.goto( url.toString() );
		await page.locator( '.dp-tl-panel' ).first().waitFor();

		expect(
			await divergences( page, entriesFor( 'narrow' ) ),
			'The chart below 700px of container is the design\'s "stack" mode; ' +
				'its numbers are in the LAYOUT NOTES at the end of TimelineChart.dc.html.'
		).toEqual( [] );
	} );
} );
