/**
 * The work template, measured against the design instead of against itself.
 *
 * `spacing.spec.ts` compares the rendered page with the site editor's canvas.
 * That is a real bug class — a one-class rule wins in one context and loses in
 * the other (ADR-0008, ADR-0011) — and it is the only thing that file claims.
 * What it cannot do, by construction, is notice that both contexts agree on the
 * wrong number. Phase 7c reported "0 divergences across 374 elements", which was
 * true, and said nothing about whether the page looked like `design-source/`.
 * It did not: the filter chips were rendering at 54px against the design's 36,
 * and every mono caps label in the chart was four pixels taller than it should
 * have been.
 *
 * So this file has a different baseline. `tests/e2e/fixtures/` holds a JSON
 * baseline generated by `composer design:baseline`, which reads the inline
 * `style` attributes out of `design-source/*.dc.html` and writes them down
 * beside the theme selector that plays the same role. Nothing in it was chosen
 * by this theme; every value is the design's own text, `var()` names and all.
 *
 * **How a value is checked.** Each entry names one element. The element's
 * computed style is read first, then a probe of the same tag is appended beside
 * it, given the design's declarations verbatim, and read too. Both are resolved
 * by one engine, in one inherited font context, at one viewport — which is what
 * makes `ch`, `em`, `clamp()` of a viewport unit and `color-mix()` comparable at
 * all, instead of being re-implemented in PHP and compared against a number that
 * would rot. Only the longhands the design's own declarations expand to are
 * compared; the CSSOM says which those are, so nothing is asserted that the
 * design did not say.
 *
 * **The half that is not in the markup.** A component's most interesting values
 * — `rowStyle`, `orgStyle`, `legendStyle`, `headlineStyle` — are computed in the
 * design's own script block. This file used to say those "never reach the
 * exported file", which was false: the 2026-08-19 import had dropped every
 * `<script type="text/x-dc">`, and nobody had re-fetched. They are back as
 * `design-source/components/*.logic.js`, `DesignBaseline` evaluates them, and
 * roughly half of each component is asserted here for the first time. Where the
 * theme legitimately differs, the baseline carries a `skip` with the reason
 * written out; where an entry pins only part of an object, it carries an
 * `omitted` list naming the rest. See `docs/adr/0012-design-parity-harness.md`.
 *
 * **Five passes, not two.** A sweep is a page, a width and an open state,
 * because all three change what the design says. Until 2026-08-23 both passes
 * navigated with `dp-open=all`, so `.dp-tl-row:not([open])` matched nothing and
 * every closed state in the design was unasserted; and the front page had no
 * pass at all.
 *
 * External dependencies
 */
import * as fs from 'fs';
import * as path from 'path';
import type { Page } from '@playwright/test';
import { test, expect } from '@wordpress/e2e-test-utils-playwright';

/**
 * Internal dependencies
 */
import { SHARED_SHIPS, sharedWorkPageUrl } from './global-setup';

/** One element of the design, and the theme element that plays its part. */
type Entry = {
	id: string;
	sweep: string;
	selector: string;
	source: { file: string; anchor: string };
	declarations: Record< string, string >;
	skip?: Record< string, string >;
	divergence?: Record< string, string >;
	omitted?: string[];
	note?: string;
};

/** A page, a width and an open state. */
type Sweep = { page: string; width: number; open: string };

/** The generated baseline. */
type Baseline = {
	sweeps: Record< string, Sweep >;
	entries: Entry[];
};

const BASELINE: Baseline = JSON.parse(
	fs.readFileSync(
		path.join( process.cwd(), 'tests/e2e/fixtures/design-baseline.json' ),
		'utf8'
	)
);

/** Logged out: the admin bar is chrome no reader sees, and it moves the page down. */
const READER = { cookies: [], origins: [] };

/** The work page's URL, looked up once per worker. */
let workPage = '';

/** The front page, which is the site root. */
const homePage = ( process.env.WP_BASE_URL ?? 'http://localhost:8889' ) + '/';

/**
 * Fail loudly if the reduced-motion preference did not reach the document.
 *
 * Every measurement below depends on it — see the note above `beforeEach` — so
 * a preference that silently stopped applying would turn this file into a test
 * that samples whatever frame it lands on.
 *
 * @param page The page.
 */
async function assertMotionIsOff( page: Page ): Promise< void > {
	expect(
		await page.evaluate(
			() =>
				window.matchMedia( '(prefers-reduced-motion: reduce)' ).matches
		),
		'The reduced-motion preference did not reach the document, so a ' +
			'measurement here can land mid-transition.'
	).toBe( true );
}

/**
 * Compare one viewport's worth of entries against the page, and say what differs.
 *
 * Returns one line per divergent property, naming the design file it came from,
 * so a failure is actionable without opening anything.
 *
 * @param page    The page, already at the right width and URL.
 * @param entries The baseline entries for this viewport.
 */
async function divergences(
	page: Page,
	entries: Entry[]
): Promise< string[] > {
	return page.evaluate( ( rows: Entry[] ) => {
		const camel = ( property: string ): string =>
			property.replace( /-([a-z])/g, ( _match, letter: string ) =>
				letter.toUpperCase()
			);

		/*
		 * A transition list serialises one value per transitioned property, so
		 * adding a fourth property to a control — which the theme does on the
		 * pills, because their current state changes background as well as
		 * colour — makes every longhand in the family differ by length while
		 * saying nothing about whether the duration or the easing is the
		 * design's. The durations and curves are tokens, so `tokens.spec.ts`
		 * already holds them, and what motion has to honour is checked by
		 * `timeline.spec.ts` under `prefers-reduced-motion`.
		 */
		const IGNORED = /^(transition|animation)/;

		const found: string[] = [];

		for ( const entry of rows ) {
			const target = document.querySelector( entry.selector );

			if ( ! target ) {
				found.push(
					`${ entry.id } — the design draws this and "${ entry.selector }" matched ` +
						`nothing on the page. [${ entry.source.file }]`
				);
				continue;
			}

			const parent = target.parentElement;

			if ( ! parent ) {
				found.push(
					`${ entry.id } — "${ entry.selector }" has no parent to probe beside.`
				);
				continue;
			}

			/*
			 * The probe is the same tag, so the user-agent stylesheet applies to
			 * both, and a sibling of the target, so both inherit from the same
			 * element. It carries no class, so nothing in the theme reaches it:
			 * what it computes is the design's declarations and nothing else.
			 */
			const probe = document.createElement( target.tagName );

			for ( const [ property, value ] of Object.entries(
				entry.declarations
			) ) {
				probe.style.setProperty( property, value );
			}

			// The CSSOM expands the design's shorthands for us, which is the
			// list of longhands the design actually constrains.
			const constrained = Array.from( probe.style )
				.map( camel )
				.filter( ( property ) => ! IGNORED.test( property ) );
			const theme: Record< string, string > = {};
			const themeStyle = window.getComputedStyle( target );

			// Read before the probe is in the document, so inserting it cannot
			// move the element it is being compared against.
			for ( const property of constrained ) {
				theme[ property ] = themeStyle.getPropertyValue(
					property.replace( /[A-Z]/g, ( c ) => '-' + c.toLowerCase() )
				);
			}

			parent.appendChild( probe );

			const probeStyle = window.getComputedStyle( probe );
			const design: Record< string, string > = {};

			for ( const property of constrained ) {
				design[ property ] = probeStyle.getPropertyValue(
					property.replace( /[A-Z]/g, ( c ) => '-' + c.toLowerCase() )
				);
			}

			probe.remove();

			for ( const property of constrained ) {
				if ( entry.skip && entry.skip[ property ] ) {
					continue;
				}

				/*
				 * A property the theme deliberately does not take from the
				 * design. Stronger than a skip, and there is one: the year
				 * axis. See the named test below, which is what stops this
				 * becoming a quiet way to switch an assertion off.
				 */
				if ( entry.divergence && entry.divergence[ property ] ) {
					continue;
				}

				if ( design[ property ] === theme[ property ] ) {
					continue;
				}

				found.push(
					`${ entry.id } (${ entry.selector }) ${ property } — ` +
						`design: ${ design[ property ] } / theme: ${ theme[ property ] } ` +
						`[${ entry.source.file }]`
				);
			}
		}

		return found;
	}, entries );
}

/**
 * One sweep by name, or a failure that says which one is missing.
 *
 * @param name The baseline's name for it.
 */
function sweepNamed( name: string ): Sweep {
	const sweep = BASELINE.sweeps[ name ];

	if ( ! sweep ) {
		throw new Error(
			`The baseline has no "${ name }" sweep. Run: composer design:baseline`
		);
	}

	return sweep;
}

/**
 * The entries measured in one pass.
 *
 * @param sweep The baseline's name for it.
 */
function entriesFor( sweep: string ): Entry[] {
	return BASELINE.entries.filter( ( entry ) => entry.sweep === sweep );
}

/**
 * Put the page at one sweep's width, page and open state.
 *
 * @param page  The page.
 * @param sweep Which pass.
 */
async function visit( page: Page, sweep: Sweep ): Promise< void > {
	await page.setViewportSize( { width: sweep.width, height: 1200 } );

	const url = new URL( 'home' === sweep.page ? homePage : workPage );

	if ( 'none' !== sweep.open ) {
		url.searchParams.set( 'dp-open', sweep.open );
	}

	await page.goto( url.toString() );

	if ( 'work' === sweep.page && 'none' !== sweep.open ) {
		await page.locator( '.dp-tl-panel' ).first().waitFor();
	}

	await assertMotionIsOff( page );
}

test.describe( 'the work template against design-source/', () => {
	test.use( { storageState: READER } );

	/*
	 * This file establishes nothing. The chart it measures is drawn from a
	 * *global* query — every published role and shipped thing on the site — and
	 * the cards above it from another one that holds three, so a fixture of its
	 * own would be a fixture in everybody's page. It reads the one
	 * `tests/e2e/global-setup.ts` establishes, which nothing creates during a
	 * run and nothing deletes. ADR-0013.
	 */
	test.beforeAll( async ( { requestUtils } ) => {
		workPage = await sharedWorkPageUrl( requestUtils );
	} );

	/*
	 * Measured with motion switched off, and this is a correctness requirement
	 * rather than a courtesy.
	 *
	 * `.dp-tl-row` carries `transition: background`, and the tint it transitions
	 * to is declared inside a container query. A container query cannot be
	 * resolved until the container has been laid out, so the row's background
	 * changes once *after* first paint — which starts a transition on a page
	 * nobody has touched. Sample during it and the row reports about 60% of the
	 * design's alpha, serialised in oklab because that is the interpolation
	 * space, and the sweep reports a divergence that is really a timestamp.
	 * Under several workers the machine is slow enough to land there.
	 *
	 * `base.css` blunts every transition to 0.01ms under this preference and
	 * `components.css` takes the chart's out altogether, so with it set there is
	 * no in-between state to sample. Nothing this file pins is motion:
	 * `divergences()` already drops the transition and animation longhands, and
	 * the only non-motion rule in either reduced-motion block is a transform on
	 * the 404 page's button, which is not on this page and not in the baseline.
	 */
	test.beforeEach( async ( { page } ) => {
		await page.emulateMedia( { reducedMotion: 'reduce' } );
	} );

	test( 'the baseline is the design, and there is enough of it to mean something', () => {
		expect(
			BASELINE.entries.length,
			'The generated baseline is empty. Run: composer design:baseline'
		).toBeGreaterThan( 120 );

		// Every sweep the fixture declares has something to measure. A sweep
		// with no entries is a pass that runs, navigates and asserts nothing.
		for ( const name of Object.keys( BASELINE.sweeps ) ) {
			expect(
				entriesFor( name ).length,
				`The "${ name }" sweep has no entries.`
			).toBeGreaterThan( 0 );
		}

		// Every entry belongs to a sweep that exists.
		for ( const entry of BASELINE.entries ) {
			expect(
				BASELINE.sweeps[ entry.sweep ],
				`${ entry.id } names a sweep that does not exist.`
			).toBeTruthy();
		}
	} );

	/*
	 * The one place the theme deliberately disagrees with the design, asserted
	 * as a disagreement rather than left as an absence.
	 *
	 * `.dp-tl-years` is `display: flex; justify-content: space-between` in
	 * `TimelineChart.dc.html`, and the theme draws it as a grid of equal
	 * columns, because the design's own two halves are on different scales: the
	 * bars advance 1/13 of the track per year and the labels 1/12, so the last
	 * label ends up 7.7% to the right of the year it names. ADR-0014 has the
	 * arithmetic and David's decision.
	 *
	 * The failure this test exists to prevent is the *quiet* version of that
	 * change: deleting the entry, so the sweep goes green because nothing is
	 * measured. The second amendment to ADR-0012 is four days of exactly that.
	 * So the entry stays, it carries a reason per property, and every reason
	 * names an ADR — `DesignBaseline::assert_recorded()` refuses one that does
	 * not, and this asserts the same thing from the side that consumes it.
	 */
	test( 'the axis divergence is recorded, not deleted', () => {
		const years = BASELINE.entries.find(
			( entry ) => entry.id === 'chart.years'
		);

		expect(
			years,
			'The `chart.years` entry is gone. A divergence from design-source/ is ' +
				'recorded in the fixture with its reason; it is not removed. ' +
				'See docs/adr/0014-the-year-axis-and-the-bars-share-one-scale.md.'
		).toBeTruthy();

		// The design still says what it said. If this stops matching, the design
		// moved and the divergence needs re-reading rather than re-generating.
		expect( years?.declarations ).toEqual( {
			display: 'flex',
			'justify-content': 'space-between',
		} );

		expect(
			Object.keys( years?.divergence ?? {} ).sort(),
			"Both of the design's declarations on this element are diverged from, " +
				'and each one says so.'
		).toEqual( [ 'display', 'justifyContent' ] );

		for ( const [ property, reason ] of Object.entries(
			years?.divergence ?? {}
		) ) {
			expect(
				reason,
				`The divergence on ${ property } names no ADR.`
			).toMatch( /ADR-\d{4}/ );
		}

		// And nothing else in the fixture has quietly grown one. The four bar
		// entries are the second recorded divergence: ADR-0022 shrinks the
		// design's 64px/40px floor, which is worth about a year on this page's
		// track and drew every sub-year role a year long.
		expect(
			BASELINE.entries
				.filter( ( entry ) => entry.divergence )
				.map( ( entry ) => entry.id ),
			'A third entry diverges from the design. That is a decision, and it ' +
				'needs an ADR and a line in this test before it needs a fixture.'
		).toEqual( [
			'chart.years',
			'row.role.bar.open',
			'row.role.bar.closed',
			'row.ship.bar.open',
			'row.ship.bar.closed',
		] );

		// The bar divergence is one property on each of the four, and no more:
		// everything else about a bar still has to match the design exactly.
		for ( const id of [
			'row.role.bar.open',
			'row.role.bar.closed',
			'row.ship.bar.open',
			'row.ship.bar.closed',
		] ) {
			const bar = BASELINE.entries.find( ( entry ) => entry.id === id );

			expect(
				Object.keys( bar?.divergence ?? {} ),
				`${ id } diverges on more than the floor.`
			).toEqual( [ 'minWidth' ] );

			expect(
				bar?.divergence?.minWidth,
				`The divergence on ${ id } names no ADR.`
			).toMatch( /ADR-\d{4}/ );
		}
	} );

	/*
	 * The guard on everything below it.
	 *
	 * `.dp-card` and its family are measured with `querySelector`, so what they
	 * resolve to is whatever the featured loop put first — and that loop is
	 * global, ordered by `menu_order`, and holds three. If a spec ever publishes a
	 * featured `dp_ship` of its own again, this page silently starts measuring
	 * that spec's card instead of the fixture's, and the sweep either passes on
	 * the wrong element or fails somewhere that says nothing about why.
	 *
	 * Naming the three, in order, is what turns that back into a sentence: the
	 * cards under measurement are the ones nobody owns.
	 */
	test( 'the cards it measures are the fixture nobody owns', async ( {
		page,
	} ) => {
		await page.setViewportSize( {
			width: sweepNamed( 'bars' ).width,
			height: 1200,
		} );
		await page.goto( workPage );

		await expect(
			page.locator( '.dp-cards .dp-card-title' ),
			'Something published a featured dp_ship during the run. The featured ' +
				'loop is global; the three cards belong to tests/e2e/global-setup.ts ' +
				'and to nothing else. See docs/adr/0013-one-fixture-nobody-owns.md.'
		).toHaveText( SHARED_SHIPS.map( ( ship ) => ship.title ) );
	} );

	/*
	 * One test per sweep, and the list of sweeps comes out of the fixture rather
	 * than out of this file. Adding a pass is then a change to the generator —
	 * the thing that reads the design — instead of a change here, which is what
	 * kept `closed` and `home` unwritten for as long as they were.
	 */
	for ( const [ name, sweep ] of Object.entries( BASELINE.sweeps ) ) {
		test( `the ${ name } pass matches the design it was drawn from`, async ( {
			page,
		} ) => {
			await visit( page, sweep );

			expect(
				await divergences( page, entriesFor( name ) ),
				'Each line is one property of one element that does not have the value ' +
					'design-source/ gives it. Fix the theme, or — if the design has moved — ' +
					're-import and run `composer design:baseline`.'
			).toEqual( [] );
		} );
	}

	/*
	 * The two things the probe cannot answer, asserted on the rendered box.
	 *
	 * `recordGridStyle` is `repeat(3, minmax(0, 1fr))` and the theme's rule says
	 * the same words, but the two cannot be compared as resolved track lists: the
	 * design draws the strip as a `<div>` and the theme as a `<ul>`, the probe is
	 * the same tag as its target, and the user agent's 40px list indent — which
	 * `.dp-record` zeroes — makes the probe's box 40px narrower. What the rule is
	 * *for* is that "3 / 2 / 1 all divide evenly, so no cell is ever orphaned on
	 * its own row", and that is a property of the rendered columns.
	 *
	 * The chevron is the same shape of problem: `translateY(-50%)` is half of an
	 * element's own height and the probe has none, so the rotation that says
	 * which way it points travels in a shorthand the sweep has to skip.
	 */
	test( 'the record strip is three equal columns, and the chevron turns over', async ( {
		page,
	} ) => {
		await page.setViewportSize( {
			width: sweepNamed( 'home' ).width,
			height: 1200,
		} );
		await page.goto( homePage );

		const columns = await page.evaluate( () => {
			const strip = document.querySelector( '.dp-record' );

			return strip
				? window
						.getComputedStyle( strip )
						.gridTemplateColumns.split( ' ' )
						.map( ( track ) => Math.round( parseFloat( track ) ) )
				: [];
		} );

		expect( columns ).toHaveLength( 3 );
		expect(
			new Set( columns ).size,
			`Three tracks, ${ columns.join( '/' ) }`
		).toBe( 1 );

		const sweep = sweepNamed( 'stack' );

		await visit( page, sweep );

		const chevrons = await page.evaluate( () => {
			const open = document.querySelector(
				'.dp-tl-row[open] .dp-tl-chevron'
			);

			return open ? window.getComputedStyle( open ).transform : '';
		} );

		// rotate(180deg) is the -1 on both diagonal terms; the translation is the
		// element's own half-height and is not what this asserts.
		expect( chevrons ).toMatch( /^matrix\(-1, 0, 0, -1,/ );
	} );

	/*
	 * `SectionHead` renders a meta or an action, never both:
	 * `hasMeta: !!meta && !action` (SectionHead.logic.js). A template that put
	 * both in one head would look right in the editor and be wrong against the
	 * design, and no property sweep can see it, because the divergence is an
	 * element that should not be in the document at all.
	 */
	test( 'no section head carries a meta and an action at once', async ( {
		page,
	} ) => {
		for ( const url of [ workPage, homePage ] ) {
			await page.goto( url );

			expect(
				await page
					.locator(
						'.dp-section-head:has(.dp-section-head-action):has(.dp-section-head-meta)'
					)
					.count(),
				`A section head on ${ url } renders both a meta and an action. ` +
					'SectionHead.logic.js suppresses the meta when there is an action.'
			).toBe( 0 );
		}
	} );

	/*
	 * The one thing the property sweep above cannot see.
	 *
	 * A sweep can only compare properties the design names, and the design does
	 * not name `box-sizing` on a chip. It names `min-height: var(--target-min)`,
	 * and `_ds/tokens/spacing.css` says what that is for: "WCAG 2.5.8 (AA)
	 * requires 24px minimum. 2.5.5 (AAA) asks for 44px. Primary navigation and
	 * form controls meet 44; secondary controls such as filter chips meet 36."
	 * A target size is a property of the rendered box, so it is asserted on the
	 * rendered box.
	 *
	 * The same file settles which box: "Button, IconButton and Input all resolve
	 * to --control-h-md, so they sit flush when placed side by side. They
	 * previously differed by 2px." Three controls with different padding only sit
	 * flush if the declared height is the whole box, so the design system's
	 * control sizing is border-box. Under `content-box` these chips measured 54 —
	 * taller than the 44px primary control, which inverts the hierarchy the same
	 * paragraph describes, and which is what David saw and called huge.
	 */
	test( 'the filter chips are the target size their own token is named for', async ( {
		page,
	} ) => {
		await page.setViewportSize( {
			width: sweepNamed( 'bars' ).width,
			height: 1200,
		} );
		await page.goto( workPage );

		const measured = await page.evaluate( () => {
			const chips = Array.from(
				document.querySelectorAll< HTMLElement >( '.dp-tl-pills a' )
			);

			// The token, resolved the same way every other value in this file
			// is: by asking the browser rather than by repeating a number.
			const probe = document.createElement( 'div' );
			probe.style.height = 'var(--target-min)';
			probe.style.position = 'absolute';
			document.body.appendChild( probe );
			const target = window.getComputedStyle( probe ).height;
			probe.remove();

			return {
				target,
				heights: chips.map(
					( chip ) => window.getComputedStyle( chip ).height
				),
				boxes: chips.map(
					( chip ) => window.getComputedStyle( chip ).boxSizing
				),
			};
		} );

		expect( measured.target ).toBe( '36px' );
		expect( measured.heights.length ).toBeGreaterThan( 3 );

		expect(
			measured.boxes,
			'The design system sizes its controls border-box; see the note above.'
		).toEqual( measured.boxes.map( () => 'border-box' ) );

		expect(
			measured.heights,
			'A chip taller than --target-min is a chip whose padding and border ' +
				'were added on top of the height its token declares.'
		).toEqual( measured.heights.map( () => measured.target ) );
	} );
} );
