/**
 * The work template, measured against the design instead of against itself.
 *
 * `spacing.spec.ts` compares the rendered page with the site editor's canvas.
 * That is a real bug class — a one-class rule wins in one context and loses in
 * the other (ADR-0008, ADR-0011) — and it is the only thing that file claims.
 * What it cannot do, by construction, is notice that both contexts agree on the
 * wrong number. Phase 7c reported "0 divergences across 374 elements", which was
 * true, and said nothing about whether the page looked like `design-source/`.
 * It did not: the filter chips were rendering at 54px against the design's 36,
 * and every mono caps label in the chart was four pixels taller than it should
 * have been.
 *
 * So this file has a different baseline. `tests/e2e/fixtures/` holds a JSON
 * baseline generated by `composer design:baseline`, which reads the inline
 * `style` attributes out of `design-source/*.dc.html` and writes them down
 * beside the theme selector that plays the same role. Nothing in it was chosen
 * by this theme; every value is the design's own text, `var()` names and all.
 *
 * **How a value is checked.** Each entry names one element. The element's
 * computed style is read first, then a probe of the same tag is appended beside
 * it, given the design's declarations verbatim, and read too. Both are resolved
 * by one engine, in one inherited font context, at one viewport — which is what
 * makes `ch`, `em`, `clamp()` of a viewport unit and `color-mix()` comparable at
 * all, instead of being re-implemented in PHP and compared against a number that
 * would rot. Only the longhands the design's own declarations expand to are
 * compared; the CSSOM says which those are, so nothing is asserted that the
 * design did not say.
 *
 * **What is deliberately not pinned.** Four of the chart's styles — the legend,
 * the kind label, the org name and the shipped headline — are computed inside
 * the design tool and never reach the exported file, so there is no design value
 * to assert and this file does not invent one. Everything else the theme had to
 * decide for itself carries a `skip` in the baseline with the reason written
 * out. See `docs/adr/0012-design-parity-harness.md`.
 *
 * External dependencies
 */
import * as fs from 'fs';
import * as path from 'path';
import type { Page } from '@playwright/test';
import { test, expect } from '@wordpress/e2e-test-utils-playwright';

/**
 * Internal dependencies
 */
import { SHARED_SHIPS, sharedWorkPageUrl } from './global-setup';

/** One element of the design, and the theme element that plays its part. */
type Entry = {
	id: string;
	viewport: string;
	selector: string;
	source: { file: string; anchor: string };
	declarations: Record< string, string >;
	skip?: Record< string, string >;
	note?: string;
};

/** The generated baseline. */
type Baseline = {
	viewports: Record< string, number >;
	entries: Entry[];
};

const BASELINE: Baseline = JSON.parse(
	fs.readFileSync(
		path.join(
			process.cwd(),
			'tests/e2e/fixtures/work-design-baseline.json'
		),
		'utf8'
	)
);

/** Logged out: the admin bar is chrome no reader sees, and it moves the page down. */
const READER = { cookies: [], origins: [] };

/** The work page's URL, looked up once per worker. */
let workPage = '';

/**
 * Fail loudly if the reduced-motion preference did not reach the document.
 *
 * Every measurement below depends on it — see the note above `beforeEach` — so
 * a preference that silently stopped applying would turn this file into a test
 * that samples whatever frame it lands on.
 *
 * @param page The page.
 */
async function assertMotionIsOff( page: Page ): Promise< void > {
	expect(
		await page.evaluate(
			() =>
				window.matchMedia( '(prefers-reduced-motion: reduce)' ).matches
		),
		'The reduced-motion preference did not reach the document, so a ' +
			'measurement here can land mid-transition.'
	).toBe( true );
}

/**
 * Compare one viewport's worth of entries against the page, and say what differs.
 *
 * Returns one line per divergent property, naming the design file it came from,
 * so a failure is actionable without opening anything.
 *
 * @param page    The page, already at the right width and URL.
 * @param entries The baseline entries for this viewport.
 */
async function divergences(
	page: Page,
	entries: Entry[]
): Promise< string[] > {
	return page.evaluate( ( rows: Entry[] ) => {
		const camel = ( property: string ): string =>
			property.replace( /-([a-z])/g, ( _match, letter: string ) =>
				letter.toUpperCase()
			);

		/*
		 * A transition list serialises one value per transitioned property, so
		 * adding a fourth property to a control — which the theme does on the
		 * pills, because their current state changes background as well as
		 * colour — makes every longhand in the family differ by length while
		 * saying nothing about whether the duration or the easing is the
		 * design's. The durations and curves are tokens, so `tokens.spec.ts`
		 * already holds them, and what motion has to honour is checked by
		 * `timeline.spec.ts` under `prefers-reduced-motion`.
		 */
		const IGNORED = /^(transition|animation)/;

		const found: string[] = [];

		for ( const entry of rows ) {
			const target = document.querySelector( entry.selector );

			if ( ! target ) {
				found.push(
					`${ entry.id } — the design draws this and "${ entry.selector }" matched ` +
						`nothing on the page. [${ entry.source.file }]`
				);
				continue;
			}

			const parent = target.parentElement;

			if ( ! parent ) {
				found.push(
					`${ entry.id } — "${ entry.selector }" has no parent to probe beside.`
				);
				continue;
			}

			/*
			 * The probe is the same tag, so the user-agent stylesheet applies to
			 * both, and a sibling of the target, so both inherit from the same
			 * element. It carries no class, so nothing in the theme reaches it:
			 * what it computes is the design's declarations and nothing else.
			 */
			const probe = document.createElement( target.tagName );

			for ( const [ property, value ] of Object.entries(
				entry.declarations
			) ) {
				probe.style.setProperty( property, value );
			}

			// The CSSOM expands the design's shorthands for us, which is the
			// list of longhands the design actually constrains.
			const constrained = Array.from( probe.style )
				.map( camel )
				.filter( ( property ) => ! IGNORED.test( property ) );
			const theme: Record< string, string > = {};
			const themeStyle = window.getComputedStyle( target );

			// Read before the probe is in the document, so inserting it cannot
			// move the element it is being compared against.
			for ( const property of constrained ) {
				theme[ property ] = themeStyle.getPropertyValue(
					property.replace( /[A-Z]/g, ( c ) => '-' + c.toLowerCase() )
				);
			}

			parent.appendChild( probe );

			const probeStyle = window.getComputedStyle( probe );
			const design: Record< string, string > = {};

			for ( const property of constrained ) {
				design[ property ] = probeStyle.getPropertyValue(
					property.replace( /[A-Z]/g, ( c ) => '-' + c.toLowerCase() )
				);
			}

			probe.remove();

			for ( const property of constrained ) {
				if ( entry.skip && entry.skip[ property ] ) {
					continue;
				}

				if ( design[ property ] === theme[ property ] ) {
					continue;
				}

				found.push(
					`${ entry.id } (${ entry.selector }) ${ property } — ` +
						`design: ${ design[ property ] } / theme: ${ theme[ property ] } ` +
						`[${ entry.source.file }]`
				);
			}
		}

		return found;
	}, entries );
}

/**
 * The entries measured at one of the baseline's two widths.
 *
 * @param viewport The baseline's name for it.
 */
function entriesFor( viewport: string ): Entry[] {
	return BASELINE.entries.filter( ( entry ) => entry.viewport === viewport );
}

test.describe( 'the work template against design-source/', () => {
	test.use( { storageState: READER } );

	/*
	 * This file establishes nothing. The chart it measures is drawn from a
	 * *global* query — every published role and shipped thing on the site — and
	 * the cards above it from another one that holds three, so a fixture of its
	 * own would be a fixture in everybody's page. It reads the one
	 * `tests/e2e/global-setup.ts` establishes, which nothing creates during a
	 * run and nothing deletes. ADR-0013.
	 */
	test.beforeAll( async ( { requestUtils } ) => {
		workPage = await sharedWorkPageUrl( requestUtils );
	} );

	/*
	 * Measured with motion switched off, and this is a correctness requirement
	 * rather than a courtesy.
	 *
	 * `.dp-tl-row` carries `transition: background`, and the tint it transitions
	 * to is declared inside a container query. A container query cannot be
	 * resolved until the container has been laid out, so the row's background
	 * changes once *after* first paint — which starts a transition on a page
	 * nobody has touched. Sample during it and the row reports about 60% of the
	 * design's alpha, serialised in oklab because that is the interpolation
	 * space, and the sweep reports a divergence that is really a timestamp.
	 * Under several workers the machine is slow enough to land there.
	 *
	 * `base.css` blunts every transition to 0.01ms under this preference and
	 * `components.css` takes the chart's out altogether, so with it set there is
	 * no in-between state to sample. Nothing this file pins is motion:
	 * `divergences()` already drops the transition and animation longhands, and
	 * the only non-motion rule in either reduced-motion block is a transform on
	 * the 404 page's button, which is not on this page and not in the baseline.
	 */
	test.beforeEach( async ( { page } ) => {
		await page.emulateMedia( { reducedMotion: 'reduce' } );
	} );

	test( 'the baseline is the design, and there is enough of it to mean something', () => {
		expect(
			BASELINE.entries.length,
			'The generated baseline is empty. Run: composer design:baseline'
		).toBeGreaterThan( 40 );

		expect( entriesFor( 'desktop' ).length ).toBeGreaterThan( 40 );
		expect( entriesFor( 'narrow' ).length ).toBeGreaterThan( 0 );
	} );

	/*
	 * The guard on everything below it.
	 *
	 * `.dp-card` and its family are measured with `querySelector`, so what they
	 * resolve to is whatever the featured loop put first — and that loop is
	 * global, ordered by `dp_end`, and holds three. If a spec ever publishes a
	 * featured `dp_ship` of its own again, this page silently starts measuring
	 * that spec's card instead of the fixture's, and the sweep either passes on
	 * the wrong element or fails somewhere that says nothing about why.
	 *
	 * Naming the three, in order, is what turns that back into a sentence: the
	 * cards under measurement are the ones nobody owns.
	 */
	test( 'the cards it measures are the fixture nobody owns', async ( {
		page,
	} ) => {
		await page.setViewportSize( {
			width: BASELINE.viewports.desktop,
			height: 1200,
		} );
		await page.goto( workPage );

		await expect(
			page.locator( '.dp-cards .dp-card-title' ),
			'Something published a featured dp_ship during the run. The featured ' +
				'loop is global; the three cards belong to tests/e2e/global-setup.ts ' +
				'and to nothing else. See docs/adr/0013-one-fixture-nobody-owns.md.'
		).toHaveText( SHARED_SHIPS.map( ( ship ) => ship.title ) );
	} );

	test( 'bars mode matches the design it was drawn from', async ( {
		page,
	} ) => {
		await page.setViewportSize( {
			width: BASELINE.viewports.desktop,
			height: 1200,
		} );

		const url = new URL( workPage );
		url.searchParams.set( 'dp-open', 'all' );

		await page.goto( url.toString() );
		await page.locator( '.dp-tl-panel' ).first().waitFor();
		await assertMotionIsOff( page );

		expect(
			await divergences( page, entriesFor( 'desktop' ) ),
			'Each line is one property of one element that does not have the value ' +
				'design-source/ gives it. Fix the theme, or — if the design has moved — ' +
				're-import and run `composer design:baseline`.'
		).toEqual( [] );
	} );

	/*
	 * The one thing the property sweep above cannot see.
	 *
	 * A sweep can only compare properties the design names, and the design does
	 * not name `box-sizing` on a chip. It names `min-height: var(--target-min)`,
	 * and `_ds/tokens/spacing.css` says what that is for: "WCAG 2.5.8 (AA)
	 * requires 24px minimum. 2.5.5 (AAA) asks for 44px. Primary navigation and
	 * form controls meet 44; secondary controls such as filter chips meet 36."
	 * A target size is a property of the rendered box, so it is asserted on the
	 * rendered box.
	 *
	 * The same file settles which box: "Button, IconButton and Input all resolve
	 * to --control-h-md, so they sit flush when placed side by side. They
	 * previously differed by 2px." Three controls with different padding only sit
	 * flush if the declared height is the whole box, so the design system's
	 * control sizing is border-box. Under `content-box` these chips measured 54 —
	 * taller than the 44px primary control, which inverts the hierarchy the same
	 * paragraph describes, and which is what David saw and called huge.
	 */
	test( 'the filter chips are the target size their own token is named for', async ( {
		page,
	} ) => {
		await page.setViewportSize( {
			width: BASELINE.viewports.desktop,
			height: 1200,
		} );
		await page.goto( workPage );

		const measured = await page.evaluate( () => {
			const chips = Array.from(
				document.querySelectorAll< HTMLElement >( '.dp-tl-pills a' )
			);

			// The token, resolved the same way every other value in this file
			// is: by asking the browser rather than by repeating a number.
			const probe = document.createElement( 'div' );
			probe.style.height = 'var(--target-min)';
			probe.style.position = 'absolute';
			document.body.appendChild( probe );
			const target = window.getComputedStyle( probe ).height;
			probe.remove();

			return {
				target,
				heights: chips.map(
					( chip ) => window.getComputedStyle( chip ).height
				),
				boxes: chips.map(
					( chip ) => window.getComputedStyle( chip ).boxSizing
				),
			};
		} );

		expect( measured.target ).toBe( '36px' );
		expect( measured.heights.length ).toBeGreaterThan( 3 );

		expect(
			measured.boxes,
			'The design system sizes its controls border-box; see the note above.'
		).toEqual( measured.boxes.map( () => 'border-box' ) );

		expect(
			measured.heights,
			'A chip taller than --target-min is a chip whose padding and border ' +
				'were added on top of the height its token declares.'
		).toEqual( measured.heights.map( () => measured.target ) );
	} );

	test( 'stack mode matches the design it was drawn from', async ( {
		page,
	} ) => {
		await page.setViewportSize( {
			width: BASELINE.viewports.narrow,
			height: 1200,
		} );

		const url = new URL( workPage );
		url.searchParams.set( 'dp-open', 'all' );

		await page.goto( url.toString() );
		await page.locator( '.dp-tl-panel' ).first().waitFor();
		await assertMotionIsOff( page );

		expect(
			await divergences( page, entriesFor( 'narrow' ) ),
			'The chart below 700px of container is the design\'s "stack" mode; ' +
				'its numbers are in the LAYOUT NOTES at the end of TimelineChart.dc.html.'
		).toEqual( [] );
	} );
} );
