<?php
/**
 * Generator for the work template's design-parity baseline.
 *
 * @package DP\Tests
 */

declare( strict_types=1 );

namespace DP\Tests\Support;

use RuntimeException;

/**
 * Builds `tests/e2e/fixtures/work-design-baseline.json` from `design-source/`.
 *
 * The map below is the only hand-written part, and it is deliberately the only
 * hand-written part. Mapping a design element to a theme element is a judgement
 * about *role* — the design's "kind label" is the theme's `.dp-tl-kind` — and no
 * generator can make it. Everything to the right of that judgement is read out
 * of the design source: the anchor names one element of one `.dc.html`, and the
 * declarations come back exactly as the design wrote them, `var()` names intact.
 *
 * Three consequences, all of them the point:
 *
 * **No value in the fixture was chosen by this theme.** If a number is pinned,
 * `design-source/` said it. If the design does not say it, it is not pinned, and
 * where the theme had to supply something anyway the entry carries a `skip` with
 * the reason. See `docs/adr/0012-design-parity-harness.md`.
 *
 * **Where the theme disagrees with the design on purpose, it says so out loud.**
 * A `divergence` is not a `skip`: a skip means the design is silent or
 * self-contradictory and the theme had to pick, a divergence means the design is
 * perfectly clear and David overrode it. There is exactly one — the year axis,
 * ADR-0014 — and it is recorded rather than deleted, because an entry that is
 * not in the fixture cannot fail and a sweep that measures nothing passes.
 * `assert_recorded()` refuses a divergence whose reason names no ADR.
 *
 * **An anchor that stops matching is a failure, not a silent gap.** The design
 * moves by re-import, and `composer design:check` fails the moment an element it
 * names has changed shape, which is the signal to re-read the component.
 *
 * **Values stay unevaluated.** `var(--fs-xs)` is written to the fixture as
 * `var(--fs-xs)`, and `tests/e2e/design-parity.spec.ts` hands it to the browser
 * to resolve. That is what makes `ch`, `em`, `clamp()` of a viewport unit and
 * `color-mix()` assertable at all: both sides are resolved by one engine, in one
 * font context, at one viewport, instead of being re-implemented in PHP and
 * compared to a number that would rot.
 */
final class DesignBaseline {

	/**
	 * Path of the generated fixture, relative to the repository root.
	 */
	public const OUTPUT = 'tests/e2e/fixtures/design-baseline.json';

	/**
	 * The four passes the baseline is measured in.
	 *
	 * A pass is a page, a width and an open state, because all three change what
	 * the design says. `bars` is wide enough that every `clamp()` has reached its
	 * ceiling and the chart's container query is in bars mode; `stack` is inside
	 * the design's own 700px breakpoint. `closed` is the same width as `bars`
	 * with nothing expanded — until 2026-08-23 both chart passes navigated with
	 * `dp-open=all`, so `.dp-tl-row:not([open])` matched nothing and every closed
	 * state in the design went unasserted. `home` is the front page, which had no
	 * pass at all.
	 *
	 * @var array<string, array{page: string, width: int, open: string}>
	 */
	private const SWEEPS = array(
		'bars'         => array(
			'page'  => 'work',
			'width' => 1600,
			'open'  => 'all',
		),
		'stack'        => array(
			'page'  => 'work',
			'width' => 520,
			'open'  => 'all',
		),
		'bars-closed'  => array(
			'page'  => 'work',
			'width' => 1600,
			'open'  => 'none',
		),
		'stack-closed' => array(
			'page'  => 'work',
			'width' => 520,
			'open'  => 'none',
		),
		'home'         => array(
			'page'  => 'home',
			'width' => 1600,
			'open'  => 'none',
		),
	);

	/**
	 * Constructor.
	 *
	 * @param DesignMarkup $markup The design's component markup.
	 * @param DesignLogic  $logic  The design's computed style objects.
	 */
	public function __construct(
		private readonly DesignMarkup $markup,
		private readonly DesignLogic $logic
	) {}

	/**
	 * Build a baseline for the repository at `$root`.
	 *
	 * @param string $root Absolute path to the repository root.
	 * @return self
	 */
	public static function for_repository( string $root ): self {
		return new self( DesignMarkup::from_repository( $root ), DesignLogic::from_repository( $root ) );
	}

	/**
	 * Render the fixture.
	 *
	 * @return string JSON, newline-terminated.
	 *
	 * @throws RuntimeException If the JSON cannot be encoded.
	 */
	public function render(): string {
		$entries = array();

		foreach ( $this->map() as $definition ) {
			$entries[] = $this->entry( $definition );
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.json_encode_json_encode -- the generator runs from the command line, before WordPress exists.
		$json = json_encode(
			array(
				'$comment' => 'Generated by `composer design:baseline` from design-source/. Never hand-edited; '
					. 'see tests/Support/DesignBaseline.php and docs/adr/0012-design-parity-harness.md.',
				'sweeps'   => self::SWEEPS,
				'entries'  => $entries,
			),
			JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
		);

		if ( ! is_string( $json ) ) {
			throw new RuntimeException( 'The design baseline could not be encoded as JSON.' );
		}

		return $json . "\n";
	}

	/**
	 * Resolve one map definition into a fixture entry.
	 *
	 * @param array<string, mixed> $definition One row of the map.
	 * @return array<string, mixed>
	 *
	 * @throws RuntimeException If the definition is malformed.
	 */
	private function entry( array $definition ): array {
		$computed = isset( $definition['logic'] ) && is_array( $definition['logic'] ) ? $definition['logic'] : array();
		$file     = array() === $computed ? self::text( $definition, 'file' ) : '';
		$xpath    = isset( $definition['xpath'] ) ? self::text( $definition, 'xpath' ) : '';
		$omitted  = array();

		if ( array() !== $computed ) {
			/*
			 * A computed style, read out of the design's own script block.
			 *
			 * This is the half of every component that is not in its markup, and
			 * for four days it was the half nothing asserted: the 2026-08-19
			 * import dropped every `<script type="text/x-dc">`, ADR-0012 recorded
			 * the styles as unrecoverable, and three audits passed over them. The
			 * blocks are back as `design-source/components/*.logic.js` and
			 * `DesignLogic` evaluates them, so a value here is still the design's
			 * text rather than a transcription of it.
			 *
			 * `env` is the only hand-written part, and it is the same kind of
			 * judgement as the selector beside it: which of the three modes, and
			 * which accent, this entry is asserting.
			 */
			$name    = self::text( $computed, 'name' );
			$source  = self::text( $computed, 'file' );
			$ordinal = isset( $computed['ordinal'] ) && is_int( $computed['ordinal'] ) ? $computed['ordinal'] : 1;
			$env     = isset( $computed['env'] ) && is_array( $computed['env'] ) ? $computed['env'] : array();
			$only    = self::strings( $computed, 'only' );

			$declarations = $this->logic->declarations( $source, $name, $ordinal, $env, $only );
			$file         = $source;
			$anchor       = sprintf(
				'%s%s, computed with %s',
				$name,
				1 === $ordinal ? '' : sprintf( ' (occurrence %d)', $ordinal ),
				array() === $env ? 'no bindings' : self::bindings( $env )
			);

			/*
			 * What the entry left out, said out loud. A fixture that quietly
			 * asserts a subset is the failure mode this whole apparatus exists to
			 * remove, so the names it did not take are written into the file
			 * beside the ones it did.
			 */
			foreach ( $this->logic->properties( $source, $name, $ordinal, $env ) as $property ) {
				if ( ! isset( $declarations[ $property ] ) ) {
					$omitted[] = $property;
				}
			}
		} elseif ( '' === $xpath ) {
			/*
			 * A prose entry. `TimelineChart.dc.html` closes with a block of
			 * LAYOUT NOTES that gives numbers in words. Kept for the handful of
			 * things the design states only there.
			 */
			$declarations = self::declarations( $definition, 'declarations' );
			$anchor       = self::text( $definition, 'anchor' );
		} else {
			$declarations = $this->markup->declarations( $file, $xpath );
			$anchor       = $xpath;
		}

		foreach ( self::declarations( $definition, 'override' ) as $property => $value ) {
			$declarations[ $property ] = $value;
		}

		/*
		 * The design's own document sets `font-family` and `color` on `body` and
		 * nothing else — no line-height anywhere above a component
		 * (dpaternina.dc.html, the `<style>` block in its helmet). So an element
		 * the design gives a size and no leading is drawn in the browser's
		 * `normal` line box, and that absence is a value: `theme.json` has a root
		 * `--lh-relaxed`, which is 1.65 where the design renders about 1.2, and
		 * an element that inherits it is four pixels taller than the design draws
		 * per label. Deriving it here rather than leaving the property
		 * unasserted is what stops the harness repeating `spacing.spec.ts`'s
		 * mistake in a new form: a property the design declines to set is
		 * exactly the kind a page-versus-page test can never see.
		 */
		if ( isset( $declarations['font-size'] ) && ! isset( $declarations['line-height'] ) ) {
			$declarations['line-height'] = 'normal';
			$derived                     = array(
				'line-height' => 'Not written in the style attribute. The design declares a size here and no '
					. 'leading, and nothing above it declares one either, so this is the line box the design '
					. 'renders. See the note in tests/Support/DesignBaseline.php.',
			);
		}

		if ( array() === $declarations ) {
			throw new RuntimeException( sprintf( '%s: the anchor for "%s" yielded no declarations.', $file, self::text( $definition, 'id' ) ) );
		}

		$sweep = self::text( $definition, 'sweep' );

		if ( ! isset( self::SWEEPS[ $sweep ] ) ) {
			throw new RuntimeException( sprintf( '"%s" names a sweep that does not exist.', $sweep ) );
		}

		$entry = array(
			'id'           => self::text( $definition, 'id' ),
			'sweep'        => $sweep,
			'selector'     => self::text( $definition, 'selector' ),
			'source'       => array(
				'file'   => $file,
				'anchor' => $anchor,
			),
			'declarations' => $declarations,
		);

		if ( isset( $derived ) ) {
			$entry['derived'] = $derived;
		}

		if ( array() !== $omitted ) {
			$entry['omitted'] = $omitted;
		}

		$skip = self::declarations( $definition, 'skip' );

		if ( array() !== $skip ) {
			$entry['skip'] = $skip;
		}

		/*
		 * A property where the theme deliberately does *not* do what the design
		 * says, because David decided it should not.
		 *
		 * This is a stronger statement than `skip`, which says the design is
		 * ambiguous or contradicts itself and the theme picked a reading. A
		 * divergence says the design is unambiguous, the theme disagrees with
		 * it, and CLAUDE.md section 5's "the design wins" was overridden on
		 * purpose. There is exactly one, and it needs to stay visible: the
		 * alternative — quietly deleting the entry — leaves a hole shaped
		 * exactly like the ones the second amendment to ADR-0012 was written
		 * about, where an unasserted property looked like an asserted one.
		 *
		 * Every reason names its ADR, and `assert_recorded()` refuses a
		 * definition that does not, so a divergence cannot be added in a commit
		 * message.
		 */
		$divergence = self::declarations( $definition, 'divergence' );

		if ( array() !== $divergence ) {
			$entry['divergence'] = self::assert_recorded( $divergence, self::text( $definition, 'id' ) );
		}

		if ( isset( $definition['note'] ) ) {
			$entry['note'] = self::text( $definition, 'note' );
		}

		return $entry;
	}

	/**
	 * A divergence has to point at the decision that authorised it.
	 *
	 * @param array<string, string> $divergence Property to reason.
	 * @param string                $id         The entry, for the message.
	 * @return array<string, string>
	 *
	 * @throws RuntimeException If a reason does not name an ADR.
	 */
	private static function assert_recorded( array $divergence, string $id ): array {
		foreach ( $divergence as $property => $reason ) {
			if ( ! str_contains( $reason, 'ADR-' ) ) {
				throw new RuntimeException(
					sprintf(
						'%s diverges from the design on "%s" and its reason names no ADR. '
							. 'A deliberate disagreement with design-source/ is a decision, and a decision '
							. 'that is only in a fixture is a decision nobody can find.',
						$id,
						$property
					)
				);
			}
		}

		return $divergence;
	}

	/**
	 * Read a required string out of a map definition.
	 *
	 * @param array<string, mixed> $definition One row of the map.
	 * @param string               $key        Which field.
	 * @return string
	 *
	 * @throws RuntimeException If the field is absent or not a string.
	 */
	private static function text( array $definition, string $key ): string {
		$value = $definition[ $key ] ?? null;

		if ( ! is_string( $value ) ) {
			throw new RuntimeException( sprintf( 'The design baseline map is missing a string "%s".', $key ) );
		}

		return $value;
	}

	/**
	 * Read an optional string-to-string field out of a map definition.
	 *
	 * @param array<string, mixed> $definition One row of the map.
	 * @param string               $key        Which field.
	 * @return array<string, string>
	 */
	private static function declarations( array $definition, string $key ): array {
		$value = $definition[ $key ] ?? array();

		if ( ! is_array( $value ) ) {
			return array();
		}

		$pairs = array();

		foreach ( $value as $property => $declared ) {
			if ( is_string( $property ) && is_string( $declared ) ) {
				$pairs[ $property ] = $declared;
			}
		}

		return $pairs;
	}

	/**
	 * Read an optional list-of-strings field out of a map definition.
	 *
	 * @param array<string, mixed> $definition One row of the map.
	 * @param string               $key        Which field.
	 * @return list<string>
	 */
	private static function strings( array $definition, string $key ): array {
		$value = $definition[ $key ] ?? array();
		$items = array();

		if ( is_array( $value ) ) {
			foreach ( $value as $item ) {
				if ( is_string( $item ) ) {
					$items[] = $item;
				}
			}
		}

		return $items;
	}

	/**
	 * An environment, printed the way the anchor should read it.
	 *
	 * @param array<string, mixed> $environment The bindings.
	 * @return string
	 */
	private static function bindings( array $environment ): string {
		$pairs = array();

		foreach ( $environment as $name => $value ) {
			$pairs[] = sprintf(
				'%s = %s',
				$name,
				match ( true ) {
					is_bool( $value )   => $value ? 'true' : 'false',
					is_string( $value ) => $value,
					is_int( $value )    => (string) $value,
					is_array( $value )  => array() === $value ? '{}' : 'an object',
					default             => 'null',
				}
			);
		}

		return implode( ', ', $pairs );
	}

	/**
	 * An XPath expression selecting the one element carrying an exact style.
	 *
	 * Exact rather than `contains()`, because several of the design's labels are
	 * prefixes of each other — the year axis's span is the role's range span
	 * without its `margin-top` — and a prefix match would silently pick whichever
	 * came first.
	 *
	 * @param string $style   The complete `style` attribute value.
	 * @param int    $ordinal Which match, when the design repeats one declaration.
	 * @return string
	 */
	private static function styled( string $style, int $ordinal = 1 ): string {
		return sprintf( '(//*[@style="%s"])[%d]', $style, $ordinal );
	}

	/**
	 * An XPath expression selecting a styled element inside a styled ancestor.
	 *
	 * @param string $ancestor The ancestor's complete `style` attribute value.
	 * @param string $style    The target's complete `style` attribute value.
	 * @return string
	 */
	private static function styled_within( string $ancestor, string $style ): string {
		return sprintf( '(//*[@style="%s"]//*[@style="%s"])[1]', $ancestor, $style );
	}

	/**
	 * An XPath expression selecting a styled element that contains another.
	 *
	 * Several of the design's wrappers repeat a declaration across views — the
	 * band that closes the home page and the band that closes the blog are the
	 * same three properties — so the honest anchor is the one that says which of
	 * them by naming something inside it.
	 *
	 * @param string $style      The target's complete `style` attribute value.
	 * @param string $descendant A descendant's complete `style` attribute value.
	 * @return string
	 */
	private static function styled_around( string $style, string $descendant ): string {
		return sprintf( '(//*[@style="%s"][.//*[@style="%s"]])[1]', $style, $descendant );
	}

	/**
	 * Every element of the work template, by role.
	 *
	 * Ordered the way the page is: the hero, the featured cards, the record's
	 * head and lede, the chart's shell, a closed row, an open role, an open
	 * shipped thing, the outro, the closing band.
	 *
	 * @return list<array<string, mixed>>
	 */
	private function map(): array {
		$hero     = 'components/PageHero.dc.html';
		$head     = 'components/SectionHead.dc.html';
		$card     = 'components/WorkCard.dc.html';
		$pills    = 'components/FilterPills.dc.html';
		$chart    = 'components/TimelineChart.dc.html';
		$view     = 'dpaternina.dc.html';
		$featured = 'max-width: var(--container-lg); margin: 0 auto; padding: 24px var(--gutter) 64px';
		$record   = 'max-width: var(--container-lg); margin: 0 auto; padding: 20px var(--gutter) 120px';
		$outro    = 'display: flex; flex-wrap: wrap; align-items: baseline; justify-content: space-between; gap: 16px 24px; margin-top: 40px; padding-top: 24px; border-top: 1px solid var(--border-subtle)';
		$band     = 'max-width: var(--container-lg); margin: 0 auto; padding: clamp(96px, 14vw, 160px) var(--gutter) clamp(104px, 15vw, 168px); text-align: center';
		$mono     = 'font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-caps); color: var(--text-muted)';
		$gold     = 'font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-caps); color: var(--hue-gold)';
		$factlbl  = 'font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-caps); color: var(--text-muted); margin-bottom: 4px';
		$range    = 'font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-wide); color: var(--text-muted); margin-top: 4px';
		$tile     = 'flex: 1 1 140px; padding: 16px; border-radius: var(--radius-sm); background: var(--bg-page); border: 1px solid var(--border-subtle)';
		$logic    = 'components/TimelineChart.logic.js';
		$home     = 'dpaternina.dc.html';

		/*
		 * The bindings every computed style in the chart is read under.
		 *
		 * `isStack` and `isScroll` are the design's own mode flags, and they are
		 * the reason a computed style needs two entries rather than one: bars and
		 * stack are different assertions of the same object, and the harness read
		 * neither until 2026-08-23. `pinned` is empty outside scroll mode, which
		 * is the whole of what the spread contributes here.
		 *
		 * `accent` is content: the shared fixture's one role carries
		 * `dp_accent: pink`, so `lane.accent || var(--dp-teal)` resolves to pink
		 * on it, and every selector below says `is-accent-pink` out loud rather
		 * than trusting which lane the query draws first. `--dp-*` and not
		 * `--hue-*` because the design's own expression is a fill (CLAUDE.md §5).
		 */
		$bars    = array(
			'isStack'  => false,
			'isScroll' => false,
			'pinned'   => array(),
		);
		$stack   = array(
			'isStack'  => true,
			'isScroll' => false,
			'pinned'   => array(),
		);
		$accent  = 'var(--dp-pink)';
		$shipped = 'var(--dp-gold)';
		$labels  = array( 'labelCol' => '200px minmax(0, 1fr)' );

		/*
		 * `barStyle` also computes a bar's left edge, its width and its ceiling
		 * from the row's own dates. That is data rather than house style and it
		 * reaches the page as an inline style, written by the timeline's own Bar
		 * value object. The rest of the object is house style and is asserted;
		 * the names left out are written into the entry's `omitted`.
		 */
		$barparts = array( 'position', 'top', 'bottom', 'min-width', 'border-radius', 'box-sizing', 'overflow', 'background', 'box-shadow' );

		/*
		 * `translateY(-50%)` is half of the element's own height, and the probe
		 * is empty, so its matrix is always the identity where the theme's is
		 * -9px of an 18px glyph. The rotation — the half of the declaration that
		 * says whether the chevron points up or down — is in the same shorthand
		 * and cannot be separated from it, so it is asserted in
		 * `tests/e2e/timeline.spec.ts` on the rendered element instead.
		 */
		$chevron = array(
			'transform' => 'The design centres the chevron on its own half-height, which an empty probe does '
				. 'not have. ADR-0012: the probe cannot answer questions about the rendered box.',
		);

		/* The home page's own anchors, and the one binding its bento reads. */
		$wide       = array( 'narrow' => false );
		$homehero   = 'position: relative; max-width: var(--container-lg); margin: 0 auto; padding: var(--section-y) var(--gutter) 64px';
		$homenow    = 'max-width: var(--container-lg); margin: 0 auto; padding: 24px var(--gutter) var(--section-y)';
		$closedband = 'border-top: 1px solid var(--border-subtle); border-bottom: 1px solid var(--border-subtle); background: var(--band)';
		$openband   = 'border-top: 1px solid var(--border-subtle); background: var(--band)';
		$column     = 'max-width: var(--container-lg); margin: 0 auto; padding: var(--section-y) var(--gutter)';
		$shippedh2  = 'margin: 0 0 16px; font-family: var(--font-display); font-weight: 700; font-size: clamp(2rem, 4.5vw, 3rem); line-height: var(--lh-tight); letter-spacing: var(--ls-display)';
		$latesthead = 'display: flex; flex-wrap: wrap; align-items: baseline; justify-content: space-between; gap: 16px 24px; margin: 0 0 40px';

		$centred = array(
			'marginLeft'  => 'The design centres this column with `margin: 0 auto`. `auto` computes to a used '
				. 'value that depends on the free space beside it, so what is asserted is the `max-width` '
				. 'that creates the column and the `text-align` inside it, not the two numbers that fall out.',
			'marginRight' => 'See marginLeft.',
		);

		return array(
			/* ---- The hero ---------------------------------------------- */
			array(
				'id'           => 'hero.section',
				'sweep'        => 'bars',
				'selector'     => '.dp-hero',
				'file'         => $hero,
				'anchor'       => 'the trailing note: wrapStyle',
				'declarations' => array(
					'max-width' => 'var(--container-lg)',
					'margin'    => '0 auto',
					'padding'   => 'clamp(48px, 8vw, 80px) var(--gutter) 40px',
				),
				'skip'         => $centred,
				'note'         => 'PageHero computes wrapStyle in the design tool, so the numbers come from the '
					. "component's own closing note, for width 'lg' and tight = false, which is how the work "
					. 'view calls it.',
			),
			array(
				'id'       => 'hero.title',
				'sweep'    => 'bars',
				'selector' => 'h1.dp-hero-title',
				'file'     => $hero,
				'xpath'    => '(//h1)[1]',
				'override' => array( 'max-width' => '20ch' ),
				'note'     => 'max-width is a template hole; the work view fills it with title-max="20ch" '
					. '(dpaternina.dc.html, the isTimeline PageHero call).',
			),
			array(
				'id'       => 'hero.deck',
				'sweep'    => 'bars',
				'selector' => 'p.dp-hero-deck',
				'file'     => $hero,
				'xpath'    => self::styled( 'margin: 0; max-width: var(--measure); font-size: var(--fs-md); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),

			/* ---- Featured work ----------------------------------------- */
			array(
				'id'       => 'featured.section',
				'sweep'    => 'bars',
				'selector' => 'section.dp-work-featured',
				'file'     => $view,
				'xpath'    => self::styled( $featured ),
				'skip'     => $centred,
			),
			array(
				'id'       => 'featured.head.wrapper',
				'sweep'    => 'bars',
				'selector' => '.dp-work-featured .dp-section-head',
				'file'     => $view,
				'xpath'    => self::styled_within( $featured, 'margin-bottom: 32px' ),
				'note'     => 'The design puts the gap under the head on a wrapper around it; the theme puts it '
					. 'on the head itself, which is the same value on the same edge with one element fewer.',
			),
			array(
				'id'       => 'featured.head',
				'sweep'    => 'bars',
				'selector' => '.dp-work-featured .dp-section-head',
				'file'     => $head,
				'xpath'    => '(//div)[1]',
			),
			array(
				'id'       => 'featured.head.heading',
				'sweep'    => 'bars',
				'selector' => 'h2.dp-section-head-heading',
				'file'     => $head,
				'xpath'    => '(//h2)[1]',
			),
			array(
				'id'       => 'featured.head.meta',
				'sweep'    => 'bars',
				'selector' => '.dp-work-featured p.dp-section-head-meta',
				'file'     => $head,
				'xpath'    => self::styled( $mono . '; text-wrap: balance' ),
			),
			array(
				'id'       => 'featured.grid',
				'sweep'    => 'bars',
				'selector' => 'ul.dp-cards',
				'file'     => $view,
				'xpath'    => self::styled_within( $featured, 'display: grid; grid-template-columns: repeat(auto-fit, minmax(min(280px, 100%), 1fr)); gap: 20px' ),
				'skip'     => array(
					'gridTemplateColumns' => '`auto-fit` collapses the tracks it has no items for, and the '
						. 'probe beside the grid is empty, so the two sides are not measuring the same '
						. 'question. The track *rule* is what matters and it is identical in both '
						. 'stylesheets; what it produces is a function of how many cards David has '
						. 'marked featured, which is content.',
				),
			),
			array(
				'id'       => 'card',
				'sweep'    => 'bars',
				'selector' => '.dp-card',
				'file'     => $card,
				'xpath'    => '(//div)[1]',
				'skip'     => array(
					'cursor' => 'The design makes the whole card the control. The theme makes the title the '
						. 'link and covers the card with its `::after`, which is one tab stop instead of a '
						. "card's worth and the same target for a mouse. Delivery mechanism, not value.",
					'height' => 'A grid item stretching to its row is a used value, and the probe beside it is '
						. 'empty. `height: 100%` is asserted by the row heights being equal, which the grid '
						. 'gives for free.',
				),
			),
			array(
				'id'       => 'card.body',
				'sweep'    => 'bars',
				'selector' => '.dp-card-body',
				'file'     => $card,
				'xpath'    => self::styled( 'padding: 24px; display: flex; flex-direction: column; gap: 10px; flex: 1' ),
			),
			array(
				'id'       => 'card.meta',
				'sweep'    => 'bars',
				'selector' => '.dp-card-meta',
				'file'     => $card,
				'xpath'    => self::styled( 'display: flex; flex-wrap: wrap; gap: 4px 12px; ' . $mono ),
			),
			array(
				'id'       => 'card.year',
				'sweep'    => 'bars',
				'selector' => 'p.dp-card-year',
				'file'     => $card,
				'xpath'    => self::styled( 'color: var(--hue-gold)' ),
			),
			array(
				'id'       => 'card.title',
				'sweep'    => 'bars',
				'selector' => 'h3.dp-card-title',
				'file'     => $card,
				'xpath'    => '(//h3)[1]',
			),
			array(
				'id'       => 'card.line',
				'sweep'    => 'bars',
				'selector' => 'p.dp-card-line',
				'file'     => $card,
				'xpath'    => self::styled( 'margin: 0; flex: 1; font-size: var(--fs-sm); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),

			/* ---- The whole record -------------------------------------- */
			array(
				'id'       => 'record.section',
				'sweep'    => 'bars',
				'selector' => 'section.dp-work-record',
				'file'     => $view,
				'xpath'    => self::styled( $record ),
				'skip'     => $centred,
			),
			array(
				'id'       => 'record.head.wrapper',
				'sweep'    => 'bars',
				'selector' => '.dp-work-record .dp-section-head',
				'file'     => $view,
				'xpath'    => self::styled_within( $record, 'margin-bottom: 24px' ),
			),
			array(
				'id'       => 'record.head.meta',
				'sweep'    => 'bars',
				'selector' => '.dp-work-record p.dp-section-head-meta',
				'file'     => $head,
				'xpath'    => self::styled( $mono . '; text-wrap: balance' ),
			),
			array(
				'id'       => 'record.lede',
				'sweep'    => 'bars',
				'selector' => 'p.dp-work-lede',
				'file'     => $view,
				'xpath'    => self::styled( 'margin: 0 0 24px; max-width: var(--measure); font-size: var(--fs-base); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),

			/* ---- The chart's shell ------------------------------------- */
			array(
				'id'       => 'chart.pills',
				'sweep'    => 'bars',
				'selector' => 'ul.dp-filter-pills.dp-tl-pills',
				'file'     => $pills,
				'xpath'    => self::styled( 'display: flex; gap: 8px; flex-wrap: wrap; align-items: center' ),
			),
			array(
				'id'       => 'chart.pills.gap-below',
				'sweep'    => 'bars',
				'selector' => 'ul.dp-filter-pills.dp-tl-pills',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; gap: 8px; margin-bottom: 28px; flex-wrap: wrap; align-items: center' ),
				'note'     => 'The chart wraps FilterPills in a row of its own to carry the 28px below it; the '
					. 'theme puts that margin on the list, which is the same edge without the wrapper.',
			),
			array(
				'id'       => 'chart.pill',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-pill-extra a',
				'file'     => $pills,
				'xpath'    => self::styled( 'cursor: pointer; min-height: var(--target-min); padding: 8px 20px; border-radius: var(--radius-pill); border: 1px dashed var(--border-subtle); background: transparent; ' . $mono . '; transition: color var(--dur-base) var(--ease-standard), border-color var(--dur-base) var(--ease-standard)' ),
				'note'     => "The design's expand-all control carries the pill's whole box on an inline style, "
					. 'which is why it is the anchor for a shape the other three pills describe only in prose.',
			),
			array(
				'id'       => 'chart.card',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-card',
				'logic'    => array(
					'file' => $logic,
					'name' => 'cardStyle',
					'env'  => $bars,
				),
			),
			array(
				'id'       => 'chart.card.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-card',
				'logic'    => array(
					'file' => $logic,
					'name' => 'cardStyle',
					'env'  => $stack,
				),
			),
			array(
				'id'       => 'chart.scroller',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-scroller',
				'logic'    => array(
					'file' => $logic,
					'name' => 'scrollerStyle',
					'env'  => $bars,
				),
			),
			array(
				'id'       => 'chart.head',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-head',
				'logic'    => array(
					'file' => $logic,
					'name' => 'headStyle',
					'env'  => array_merge( $bars, $labels ),
				),
				'note'     => 'The head is a two-column grid, not a stack: the legend sits in the 200px label '
					. "column and the year axis in the track's, which is what puts the years over the bars "
					. 'without a hand-computed `padding-left`. It also carries the rule under the head, which '
					. 'the theme did not draw at all.',
			),
			array(
				'id'       => 'chart.head.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-head',
				'logic'    => array(
					'file' => $logic,
					'name' => 'headStyle',
					'env'  => array_merge( $stack, array( 'labelCol' => 'minmax(0, 1fr)' ) ),
				),
			),
			array(
				'id'       => 'chart.legend',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-legend',
				'logic'    => array(
					'file' => $logic,
					'name' => 'legendStyle',
					'env'  => $bars,
				),
			),
			array(
				'id'       => 'chart.legend.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-legend',
				'logic'    => array(
					'file' => $logic,
					'name' => 'legendStyle',
					'env'  => $stack,
				),
			),
			array(
				'id'       => 'chart.legend.swatch.role',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-swatch-role',
				'file'     => $chart,
				'xpath'    => self::styled( 'width: 8px; height: 8px; border-radius: var(--radius-xs); background: var(--dp-teal); flex: none' ),
			),
			array(
				'id'       => 'chart.legend.swatch.ship',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-swatch-ship',
				'file'     => $chart,
				'xpath'    => self::styled( 'width: 16px; height: 8px; border-radius: var(--radius-xs); background: var(--dp-gold); flex: none' ),
			),
			array(
				'id'       => 'chart.legend.key',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-key',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: inline-flex; align-items: center; gap: 8px' ),
			),
			array(
				'id'         => 'chart.years',
				'sweep'      => 'bars',
				'selector'   => '.dp-tl-years',
				'file'       => $chart,
				'xpath'      => self::styled( 'display: flex; justify-content: space-between' ),

				/*
				 * Keyed by the CSSOM's camelCase property names, the way `skip`
				 * already is: `divergences()` walks the longhands the probe's
				 * style declaration expands to, and that is the spelling it has
				 * them in.
				 */
				'divergence' => array(
					'display'        => 'ADR-0014. The design spreads the year labels with '
						. '`justify-content: space-between`, which advances 1/12 per label while its own '
						. 'bars advance 1/13 — `pos(y) = ((y - start) / (end - start + 1)) * 100`. At the '
						. 'right-hand edge the two scales are 7.7% apart, so a role running to the present '
						. 'ends at 95.4% against a "2026" label at 100% and reads as stopping a year early. '
						. 'The theme draws the row as a grid of equal columns instead, which puts label n at '
						. 'exactly pos(year n). David\'s call, 2026-08-24; not to be round-tripped through '
						. 'Claude Design.',
					'justifyContent' => 'ADR-0014. Same decision. On a grid whose columns already fill the '
						. 'container there is no free space to distribute, so the declaration is dropped '
						. 'rather than carried across as something that reads as intent and does nothing.',
				),
				'note'       => 'The only entry in this fixture where the theme deliberately disagrees with '
					. 'design-source/. The anchor is unchanged and still has to match exactly one element, so '
					. 'a re-import that moves this row still fails `composer design:check` — which is the '
					. 'signal to re-read ADR-0014 rather than to re-run the generator. What the divergence '
					. 'costs is asserted back in tests/e2e/timeline.spec.ts: every label\'s left edge is '
					. 'measured against Geometry::position() for the year it names.',
			),
			array(
				'id'       => 'chart.years.label',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-years span',
				'file'     => $chart,
				'xpath'    => self::styled( 'font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-wide); color: var(--text-muted)' ),
			),
			array(
				'id'       => 'chart.lanes',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-lanes',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; flex-direction: column; gap: 8px; padding-top: 18px' ),
			),
			array(
				'id'       => 'chart.swipe',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-swipe',
				'file'     => $chart,
				'xpath'    => self::styled( 'padding-top: 14px; margin-top: 4px; border-top: 1px solid var(--border-subtle); ' . $mono ),
				'note'     => 'Drawn only in scroll mode, which is the variant rather than the default; the '
					. 'element is in the document either way, so its box is comparable at any width.',
			),

			/* ---- A row, and the role behind it ------------------------- */
			array(
				'id'       => 'row.role.title',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-role .dp-tl-role',
				'file'     => $chart,
				'xpath'    => self::styled( 'font-size: var(--fs-xs); color: var(--text-muted)' ),
			),
			array(
				'id'       => 'row.range',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-role .dp-tl-range',
				'file'     => $chart,
				'xpath'    => self::styled( $range ),
			),
			array(
				'id'       => 'row.role.track',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-role .dp-tl-track',
				'file'     => $chart,
				'xpath'    => self::styled( 'position: relative; height: 40px; border-radius: var(--radius-sm); background: color-mix(in srgb, var(--text-primary) 3%, transparent)' ),
			),
			array(
				'id'       => 'row.ship.track',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-ship .dp-tl-track',
				'file'     => $chart,
				'xpath'    => self::styled( 'position: relative; height: 32px; border-radius: var(--radius-xs); background: color-mix(in srgb, var(--text-primary) 2%, transparent)' ),
			),

			/*
			 * ---- What the design computes, and what that cost -----------
			 *
			 * Everything from here to the panel is read out of
			 * `TimelineChart.logic.js`. Until 2026-08-23 it was read out of
			 * nothing: the import had dropped the design's script block, ADR-0012
			 * wrote the styles off as "computed inside the design tool and never
			 * reach the export", and three audits of this page passed with about
			 * half of the component unasserted. The entries the amendment pinned
			 * by hand from a screenshot are gone; the design says all of it.
			 *
			 * Each row appears twice or three times, because `rowStyle`,
			 * `orgStyle` and their neighbours are functions of the mode and of the
			 * open state, and every branch is a different assertion.
			 * -------------------------------------------------------------
			 */

			/* The lane wrapper, and the rail its shipped things hang off. */
			array(
				'id'       => 'row.lane',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-lane',
				'logic'    => array(
					'file' => $logic,
					'name' => 'wrapStyle',
					'env'  => $bars,
				),
			),
			array(
				'id'       => 'row.lane.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-lane',
				'logic'    => array(
					'file' => $logic,
					'name' => 'wrapStyle',
					'env'  => $stack,
				),
				'note'     => 'In stack mode the lane carries the hairline that separates it from the lane '
					. 'above; in bars mode the design draws none.',
			),
			array(
				'id'       => 'row.ships',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-ships',
				'logic'    => array(
					'file' => $logic,
					'name' => 'shipsWrapStyle',
					'env'  => array_merge( $bars, array( 'railPad' => 20 ) ),
				),
				'skip'     => array(
					'borderLeftStyle' => 'The design contradicts itself here and the theme follows the prose. '
						. '`shipsWrapStyle` declares padding and no border, but the comment directly above it '
						. 'says shipped items "hang off a hairline rail in every mode — an indent alone never '
						. 'read as nesting", and the closing LAYOUT NOTES say the same thing again. Two '
						. 'sentences of intent against one missing declaration: the theme keeps the rail and '
						. 'this records that it is not read from the computed style. Ask David before removing it.',
					'borderLeftWidth' => 'See borderLeftStyle.',
					'borderLeftColor' => 'See borderLeftStyle.',
				),
			),
			array(
				'id'       => 'row.ships.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-ships',
				'logic'    => array(
					'file' => $logic,
					'name' => 'shipsWrapStyle',
					'env'  => array_merge( $stack, array( 'railPad' => 16 ) ),
				),
			),

			/* The grid inside a row: the label column, then the year track. */
			array(
				'id'       => 'row.grid',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-role > .dp-tl-summary > .dp-tl-grid',
				'logic'    => array(
					'file' => $logic,
					'name' => 'gridStyle',
					'env'  => array_merge( $bars, $labels ),
				),
			),
			array(
				'id'       => 'row.grid.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-row-role > .dp-tl-summary > .dp-tl-grid',
				'logic'    => array(
					'file' => $logic,
					'name' => 'gridStyle',
					'env'  => array_merge( $stack, array( 'labelCol' => 'minmax(0, 1fr)' ) ),
				),
			),
			array(
				'id'       => 'row.grid.ship',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-ship > .dp-tl-summary > .dp-tl-grid',
				'logic'    => array(
					'file' => $logic,
					'name' => 'shipGridStyle',
					'env'  => array_merge(
						$bars,
						$labels,
						array(
							'labelW'  => 200,
							'railPad' => 20,
						)
					),
				),
				'note'     => 'A shipped thing gives the rail back out of its label column — 200 minus 20 — '
					. 'so its bar sits on the same year axis as the role bar above it.',
			),

			/* The label cell. Its gutter is the chevron's, and the chevron is stack-only. */
			array(
				'id'       => 'row.label',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-ship > .dp-tl-summary .dp-tl-label',
				'logic'    => array(
					'file' => $logic,
					'name' => 'labelCellStyle',
					'env'  => $bars,
				),
				'skip'     => array(
					'cursor' => 'The design makes the label cell the control. The theme makes the whole '
						. '`<summary>` the control, which is one tab stop, works with the scripts off, and is '
						. 'what carries the cursor. Delivery mechanism, not value.',
				),
				'note'     => 'Asserted on a shipped thing because that is the column the arithmetic is tight '
					. 'in: 180px against a longest fixture name of 170.6.',
			),
			array(
				'id'       => 'row.label.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-row-ship > .dp-tl-summary .dp-tl-label',
				'logic'    => array(
					'file' => $logic,
					'name' => 'labelCellStyle',
					'env'  => $stack,
				),
				'skip'     => array( 'cursor' => 'See row.label.' ),
			),

			/* The row box: four states, because padding and tint are functions of both. */
			array(
				'id'       => 'row.role.closed',
				'sweep'    => 'bars-closed',
				'selector' => '.dp-tl-row-role:not([open])',
				'logic'    => array(
					'file' => $logic,
					'name' => 'rowStyle',
					'env'  => array_merge(
						$bars,
						array(
							'isOpen' => false,
							'isShip' => false,
						)
					),
				),
			),
			array(
				'id'       => 'row.role.open',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-role[open]',
				'logic'    => array(
					'file' => $logic,
					'name' => 'rowStyle',
					'env'  => array_merge(
						$bars,
						array(
							'isOpen' => true,
							'isShip' => false,
						)
					),
				),
			),
			array(
				'id'       => 'row.role.open.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-row-role[open]',
				'logic'    => array(
					'file' => $logic,
					'name' => 'rowStyle',
					'env'  => array_merge(
						$stack,
						array(
							'isOpen' => true,
							'isShip' => false,
						)
					),
				),
			),
			array(
				'id'       => 'row.role.closed.stack',
				'sweep'    => 'stack-closed',
				'selector' => '.dp-tl-row-role:not([open])',
				'logic'    => array(
					'file' => $logic,
					'name' => 'rowStyle',
					'env'  => array_merge(
						$stack,
						array(
							'isOpen' => false,
							'isShip' => false,
						)
					),
				),
			),
			array(
				'id'       => 'row.ship.closed',
				'sweep'    => 'bars-closed',
				'selector' => '.dp-tl-row-ship:not([open])',
				'logic'    => array(
					'file' => $logic,
					'name' => 'rowStyle',
					'env'  => array_merge(
						$bars,
						array(
							'isOpen' => false,
							'isShip' => true,
						)
					),
				),
			),
			array(
				'id'       => 'row.ship.open',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-ship[open]',
				'logic'    => array(
					'file' => $logic,
					'name' => 'rowStyle',
					'env'  => array_merge(
						$bars,
						array(
							'isOpen' => true,
							'isShip' => true,
						)
					),
				),
			),
			array(
				'id'       => 'row.ship.open.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-row-ship[open]',
				'logic'    => array(
					'file' => $logic,
					'name' => 'rowStyle',
					'env'  => array_merge(
						$stack,
						array(
							'isOpen' => true,
							'isShip' => true,
						)
					),
				),
			),

			/* The bar. The closed fill is the one the design states in prose too. */
			array(
				'id'         => 'row.role.bar.open',
				'sweep'      => 'bars',
				'selector'   => '.dp-tl-row-role.is-accent-pink[open] .dp-tl-bar',
				'logic'      => array(
					'file' => $logic,
					'name' => 'barStyle',
					'env'  => array(
						'isOpen' => true,
						'color'  => $accent,
						'small'  => false,
					),
					'only' => $barparts,
				),
				'divergence' => array(
					'minWidth' => 'ADR-0022. The design floors a role bar at 64px, which is about a year '
						. 'on the width this page gives the track -- so every sub-year role was drawn a '
						. 'year long and two consecutive three-month roles read as concurrent. The floor '
						. 'clears a perceptual threshold; the whole row, not the bar, is the click target.',
				),
			),
			array(
				'id'         => 'row.role.bar.closed',
				'sweep'      => 'bars-closed',
				'selector'   => '.dp-tl-row-role.is-accent-pink:not([open]) .dp-tl-bar',
				'logic'      => array(
					'file' => $logic,
					'name' => 'barStyle',
					'env'  => array(
						'isOpen' => false,
						'color'  => $accent,
						'small'  => false,
					),
					'only' => $barparts,
				),
				'divergence' => array(
					'minWidth' => 'ADR-0022. The design floors a role bar at 64px, which is about a year '
						. 'on the width this page gives the track -- so every sub-year role was drawn a '
						. 'year long and two consecutive three-month roles read as concurrent. The floor '
						. 'clears a perceptual threshold; the whole row, not the bar, is the click target.',
				),
				'note'       => 'The first closed bar this harness has ever measured. Both of its sweeps used to '
					. 'navigate with `dp-open=all`, so `color-mix(in srgb, <color> 38%, var(--bg-surface))` — '
					. 'which the design states in the COLOURS block as well as computing — matched nothing.',
			),
			array(
				'id'         => 'row.ship.bar.open',
				'sweep'      => 'bars',
				'selector'   => '.dp-tl-row-ship[open] .dp-tl-bar',
				'logic'      => array(
					'file' => $logic,
					'name' => 'barStyle',
					'env'  => array(
						'isOpen' => true,
						'color'  => $shipped,
						'small'  => true,
					),
					'only' => $barparts,
				),
				'divergence' => array(
					'minWidth' => 'ADR-0022. The ship floor moves with the role floor, and for the same '
						. 'reason. Roles keep the larger of the two so a role still outranks a ship when '
						. 'both are floored, which is what the design\'s 64:40 ratio was saying.',
				),
				'note'       => 'A shipped thing\'s bar is inset 6px top and bottom against a role\'s 4 — the '
					. '`small` branch of `barStyle`, which nothing asserted before.',
			),
			array(
				'id'         => 'row.ship.bar.closed',
				'sweep'      => 'bars-closed',
				'selector'   => '.dp-tl-row-ship:not([open]) .dp-tl-bar',
				'logic'      => array(
					'file' => $logic,
					'name' => 'barStyle',
					'env'  => array(
						'isOpen' => false,
						'color'  => $shipped,
						'small'  => true,
					),
					'only' => $barparts,
				),
				'divergence' => array(
					'minWidth' => 'ADR-0022. The ship floor moves with the role floor, and for the same '
						. 'reason. Roles keep the larger of the two so a role still outranks a ship when '
						. 'both are floored, which is what the design\'s 64:40 ratio was saying.',
				),
			),

			/* The ROLE label above an open role's detail. */
			array(
				'id'       => 'row.role.kind',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-role.is-accent-pink[open] .dp-tl-kind',
				'logic'    => array(
					'file' => $logic,
					'name' => 'kindLabelStyle',
					'env'  => array( 'teal' => $accent ),
				),
				'skip'     => array(
					'textTransform' => 'See row.detail.stack: the label is a translated string, so the theme '
						. 'casts the case in CSS rather than shipping capitals a translator cannot change.',
				),
			),

			/* A row's own title, in four states across two modes. */
			array(
				'id'       => 'row.role.org.open',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-role.is-accent-pink[open] > .dp-tl-summary .dp-tl-org',
				'logic'    => array(
					'file' => $logic,
					'name' => 'orgStyle',
					'env'  => array_merge(
						$bars,
						array(
							'isOpen' => true,
							'teal'   => $accent,
						)
					),
				),
				'note'     => 'Read from the design at last. The amendment to ADR-0012 pinned this colour by '
					. 'hand from a screenshot because the export was thought not to carry `orgStyle`; it '
					. 'carries the whole object, including the display face and the tracking that nothing had '
					. 'noticed were missing.',
			),
			array(
				'id'       => 'row.role.org.closed',
				'sweep'    => 'bars-closed',
				'selector' => '.dp-tl-row-role.is-accent-pink:not([open]) > .dp-tl-summary .dp-tl-org',
				'logic'    => array(
					'file' => $logic,
					'name' => 'orgStyle',
					'env'  => array_merge(
						$bars,
						array(
							'isOpen' => false,
							'teal'   => $accent,
						)
					),
				),
			),
			array(
				'id'       => 'row.role.org.open.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-row-role.is-accent-pink[open] > .dp-tl-summary .dp-tl-org',
				'logic'    => array(
					'file' => $logic,
					'name' => 'orgStyle',
					'env'  => array_merge(
						$stack,
						array(
							'isOpen' => true,
							'teal'   => $accent,
						)
					),
				),
				'note'     => 'A role title is a size larger on a phone than it is beside a bar chart.',
			),
			array(
				'id'       => 'row.ship.org.open',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-ship[open] > .dp-tl-summary .dp-tl-org',
				'logic'    => array(
					'file'    => $logic,
					'name'    => 'orgStyle',
					'ordinal' => 2,
					'env'     => array_merge(
						$bars,
						array(
							'sOpen' => true,
							'gold'  => $shipped,
						)
					),
				),
			),
			array(
				'id'       => 'row.ship.org.closed',
				'sweep'    => 'bars-closed',
				'selector' => '.dp-tl-row-ship:not([open]) > .dp-tl-summary .dp-tl-org',
				'logic'    => array(
					'file'    => $logic,
					'name'    => 'orgStyle',
					'ordinal' => 2,
					'env'     => array_merge(
						$bars,
						array(
							'sOpen' => false,
							'gold'  => $shipped,
						)
					),
				),
				'note'     => 'A closed shipped thing is `--text-secondary`, not the `--text-primary` a role '
					. 'gets. Nothing had measured a closed row at all.',
			),
			array(
				'id'       => 'row.ship.org.open.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-row-ship[open] > .dp-tl-summary .dp-tl-org',
				'logic'    => array(
					'file'    => $logic,
					'name'    => 'orgStyle',
					'ordinal' => 2,
					'env'     => array_merge(
						$stack,
						array(
							'sOpen' => true,
							'gold'  => $shipped,
						)
					),
				),
			),

			/* The chevron, which the design draws in stack mode and nowhere else. */
			array(
				'id'       => 'row.chevron.open',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-row[open] .dp-tl-chevron',
				'logic'    => array(
					'file' => $logic,
					'name' => 'chevronStyle',
					'env'  => array( 'isOpen' => true ),
				),
				'skip'     => $chevron,
				'note'     => 'The design names the fill token for a text colour here. On dark they are the '
					. 'same value — theme.css sets `--hue-teal: var(--dp-teal)` — so the theme uses the text '
					. 'one (CLAUDE.md §5) and this still asserts the design\'s own expression. Note the design '
					. 'says teal literally rather than the row\'s accent, so an open pink lane draws a pink '
					. 'title above a teal chevron. That is the design\'s word.',
			),
			array(
				'id'       => 'row.chevron.closed',
				'sweep'    => 'stack-closed',
				'selector' => '.dp-tl-row:not([open]) .dp-tl-chevron',
				'logic'    => array(
					'file' => $logic,
					'name' => 'chevronStyle',
					'env'  => array( 'isOpen' => false ),
				),
				'skip'     => $chevron,
			),

			/* An open role's detail grid. */
			array(
				'id'       => 'row.detail.grid',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-role[open] > .dp-tl-detail',
				'logic'    => array(
					'file' => $logic,
					'name' => 'detailGridStyle',
					'env'  => array_merge( $bars, $labels ),
				),
			),
			array(
				'id'       => 'row.detail.grid.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-row-role[open] > .dp-tl-detail',
				'logic'    => array(
					'file' => $logic,
					'name' => 'detailGridStyle',
					'env'  => array_merge( $stack, array( 'labelCol' => 'minmax(0, 1fr)' ) ),
				),
			),
			array(
				'id'       => 'row.detail.prose',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-row-role[open] p.dp-tl-prose',
				'file'     => $chart,
				'xpath'    => self::styled( 'margin: 0 0 12px; max-width: var(--measure); font-size: var(--fs-base); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),
			array(
				'id'       => 'row.detail.stack',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-stack',
				'file'     => $chart,
				'xpath'    => self::styled( $mono ),
				'skip'     => array(
					'textTransform' => 'The design prints the stack from a fixture that is already upper case; '
						. 'the theme takes it from a field David types, so the case is a rule rather than a '
						. 'habit. Same rendered text, and the letter-spacing that goes with caps is asserted.',
				),
			),

			/* ---- An open shipped thing --------------------------------- */
			array(
				'id'       => 'panel',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-panel',
				'logic'    => array(
					'file' => $logic,
					'name' => 'detailStyle',
					'env'  => $bars,
				),
			),
			array(
				'id'       => 'panel.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-panel',
				'logic'    => array(
					'file' => $logic,
					'name' => 'detailStyle',
					'env'  => $stack,
				),
			),
			array(
				'id'       => 'panel.cols',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-panel-cols',
				'logic'    => array(
					'file' => $logic,
					'name' => 'detailColsStyle',
					'env'  => $bars,
				),
			),
			array(
				'id'       => 'panel.cols.stack',
				'sweep'    => 'stack',
				'selector' => '.dp-tl-panel-cols',
				'logic'    => array(
					'file' => $logic,
					'name' => 'detailColsStyle',
					'env'  => $stack,
				),
			),
			array(
				'id'       => 'panel.headline',
				'sweep'    => 'bars',
				'selector' => 'h3.dp-tl-headline',
				'logic'    => array(
					'file' => $logic,
					'name' => 'headlineStyle',
					'env'  => $bars,
				),
				'note'     => 'The headline is a size larger beside a bar chart than it is on a phone, it is '
					. 'bold, and it is tracked with `--ls-display` rather than `--ls-tight`. Three values '
					. 'nothing had ever read.',
			),
			array(
				'id'       => 'panel.headline.stack',
				'sweep'    => 'stack',
				'selector' => 'h3.dp-tl-headline',
				'logic'    => array(
					'file' => $logic,
					'name' => 'headlineStyle',
					'env'  => $stack,
				),
			),
			array(
				'id'       => 'panel.main',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-panel-main',
				'file'     => $chart,
				'xpath'    => self::styled( 'flex: 1 1 320px; min-width: 0' ),
			),
			array(
				'id'       => 'panel.aside',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-panel-aside',
				'file'     => $chart,
				'xpath'    => self::styled( 'flex: 1 1 260px; min-width: 0; display: flex; flex-direction: column; gap: 12px' ),
			),
			array(
				'id'       => 'panel.shipped',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-shipped',
				'file'     => $chart,
				'xpath'    => self::styled( $gold . '; margin-bottom: 12px' ),
				'skip'     => array( 'textTransform' => 'See row.detail.stack: the theme upper-cases a field rather than a fixture.' ),
			),
			array(
				'id'       => 'panel.prose',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-panel p.dp-tl-prose',
				'file'     => $chart,
				'xpath'    => self::styled( 'margin: 0 0 16px; max-width: var(--measure); font-size: var(--fs-base); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),
			array(
				'id'       => 'panel.bullets',
				'sweep'    => 'bars',
				'selector' => 'ul.dp-tl-bullets',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; flex-direction: column; gap: 8px; margin-bottom: 20px' ),
			),
			array(
				'id'       => 'panel.bullet',
				'sweep'    => 'bars',
				'selector' => 'li.dp-tl-bullet',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; gap: 12px; align-items: baseline; font-size: var(--fs-sm); line-height: var(--lh-relaxed); color: var(--text-secondary)' ),
				'skip'     => array(
					'display' => 'The design hangs its em dash off a real `<span>`; the theme draws it with '
						. '`::before`, which needs a track to sit in. Grid rather than flex is the delivery '
						. 'mechanism (CLAUDE.md §5); the gap, the baseline and the type are the values.',
				),
			),
			array(
				'id'       => 'panel.facts',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-facts',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; flex-wrap: wrap; gap: 20px 24px; padding-top: 16px; border-top: 1px solid var(--border-subtle)' ),
			),
			array(
				'id'       => 'panel.fact.label',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-fact-label',
				'file'     => $chart,
				'xpath'    => self::styled( $factlbl ),
				'skip'     => array( 'textTransform' => 'The label is a translated string; the theme casts the case in CSS so a translation can carry lower-case letters.' ),
			),
			array(
				'id'       => 'panel.fact.value',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-fact-value',
				'file'     => $chart,
				'xpath'    => self::styled( 'font-size: var(--fs-sm)' ),
			),
			array(
				'id'       => 'panel.fact.stack',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-fact-stack',
				'file'     => $chart,
				'xpath'    => self::styled( $gold ),
				'skip'     => array( 'textTransform' => 'See row.detail.stack.' ),
			),
			array(
				'id'       => 'panel.writeup',
				'sweep'    => 'bars',
				'selector' => 'a.dp-tl-writeup',
				'file'     => $chart,
				'xpath'    => self::styled( 'cursor: pointer; font-size: var(--fs-sm); color: var(--accent-text)' ),
			),
			array(
				'id'       => 'panel.artifact',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-artifact',
				'file'     => $chart,
				'xpath'    => self::styled( 'border-radius: var(--radius-sm); background: var(--bg-page); border: 1px solid var(--border-subtle); overflow: hidden' ),
			),
			array(
				'id'       => 'panel.artifact.head',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-artifact-head',
				'file'     => $chart,
				'xpath'    => self::styled( 'padding: 12px 16px; border-bottom: 1px solid var(--border-subtle); display: flex; justify-content: space-between; align-items: center; gap: 12px; flex-wrap: wrap' ),
			),
			array(
				'id'       => 'panel.artifact.label',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-artifact-label',
				'file'     => $chart,
				'xpath'    => self::styled( $mono, 2 ),
			),
			array(
				'id'       => 'panel.artifact.tag',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-artifact-tag',
				'file'     => $chart,
				'xpath'    => self::styled( $gold, 2 ),
				'skip'     => array( 'textTransform' => 'The tag is a translated string; see panel.fact.label.' ),
			),
			array(
				'id'       => 'panel.artifact.body',
				'sweep'    => 'bars',
				'selector' => 'pre.dp-tl-artifact-body',
				'file'     => $chart,
				'xpath'    => self::styled( 'margin: 0; padding: 16px; font-family: var(--font-mono); font-size: var(--fs-xs); line-height: var(--lh-relaxed); color: var(--text-secondary); overflow-x: auto' ),
			),
			array(
				'id'       => 'panel.stats',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-stats',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; flex-wrap: wrap; gap: 12px' ),
			),
			array(
				'id'       => 'panel.stat',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-stat',
				'file'     => $chart,
				'xpath'    => self::styled( $tile ),
			),
			array(
				'id'       => 'panel.stat.loud',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-stat-loud .dp-tl-stat-value',
				'file'     => $chart,
				'xpath'    => self::styled( 'font-family: var(--font-display); font-size: var(--fs-lg); letter-spacing: var(--ls-display); color: var(--hue-gold)' ),
			),
			array(
				'id'       => 'panel.stat.quiet',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-stat-quiet .dp-tl-stat-value',
				'file'     => $chart,
				'xpath'    => self::styled( 'font-family: var(--font-display); font-size: var(--fs-lg); letter-spacing: var(--ls-display); color: var(--text-secondary)' ),
			),
			array(
				'id'       => 'panel.stat.label',
				'sweep'    => 'bars',
				'selector' => '.dp-tl-stat-label',
				'file'     => $chart,
				'xpath'    => self::styled( $mono . '; margin-top: 4px' ),
				'skip'     => array( 'textTransform' => 'See row.detail.stack.' ),
			),

			/* ---- The outro and the closing band ------------------------ */
			array(
				'id'       => 'outro',
				'sweep'    => 'bars',
				'selector' => '.dp-work-outro',
				'file'     => $view,
				'xpath'    => self::styled( $outro ),
			),
			array(
				'id'       => 'outro.line',
				'sweep'    => 'bars',
				'selector' => '.dp-work-outro p',
				'file'     => $view,
				'xpath'    => self::styled( 'margin: 0; max-width: var(--measure); font-size: var(--fs-base); line-height: var(--lh-relaxed); color: var(--text-secondary)' ),
			),
			array(
				'id'       => 'outro.action',
				'sweep'    => 'bars',
				'selector' => '.dp-work-outro .wp-block-button__link',
				'file'     => $view,
				'xpath'    => self::styled_within( $outro, 'cursor: pointer; white-space: nowrap; font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-caps); color: var(--accent-text)' ),
				'skip'     => array( 'textTransform' => 'The label is a translated string; see panel.fact.label.' ),
			),
			array(
				'id'       => 'band',
				'sweep'    => 'bars',
				'selector' => 'section.dp-cta-band',
				'file'     => $view,
				'xpath'    => self::styled( $band ),
				'skip'     => array_merge(
					$centred,
					array(
						'maxWidth' => 'The design puts the glow on a full-bleed <section> and the column inside '
							. 'it. The theme has one element doing both, so the band cannot carry the column\'s '
							. 'max-width without cropping its own glow. Everything inside is centred or capped '
							. 'at --measure, so the only element the missing column would move is the heading, '
							. 'and it does not reach 1120px at any size. Recorded rather than closed: it is a '
							. 'real difference in shape.',
					)
				),
			),
			array(
				'id'       => 'band.title',
				'sweep'    => 'bars',
				'selector' => 'h2.dp-cta-band-title',
				'file'     => $view,
				'xpath'    => self::styled( 'margin: 0 0 16px; font-family: var(--font-display); font-weight: 700; font-size: clamp(2.25rem, 6vw, 3.75rem); line-height: var(--lh-tight); letter-spacing: var(--ls-display)' ),
			),
			array(
				'id'       => 'band.line',
				'sweep'    => 'bars',
				'selector' => 'p.dp-cta-band-line',
				'file'     => $view,
				'xpath'    => self::styled( 'margin: 0 auto 36px; max-width: var(--measure); font-size: var(--fs-base); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
				'skip'     => $centred,
			),
			array(
				'id'       => 'band.buttons',
				'sweep'    => 'bars',
				'selector' => '.dp-cta-band .wp-block-buttons',
				'file'     => $view,
				'xpath'    => self::styled( 'display: flex; flex-wrap: wrap; gap: 12px; justify-content: center' ),
			),

			/*
			 * ---- The home page ------------------------------------------
			 *
			 * ADR-0012 closed with "it covers one template", and the next review
			 * was told to inherit the harness rather than invent one. This is
			 * that: the same map, the same generator, a second page. Nothing here
			 * is new machinery.
			 * -------------------------------------------------------------
			 */
			array(
				'id'       => 'home.hero',
				'sweep'    => 'home',
				'selector' => 'section.dp-home-hero',
				'file'     => $home,
				'xpath'    => self::styled( $homehero ),
				'skip'     => $centred,
			),
			array(
				'id'       => 'home.hero.mark',
				'sweep'    => 'home',
				'selector' => '.dp-home-hero .dp-brand',
				'file'     => $home,
				'xpath'    => self::styled( 'display: flex; align-items: center; margin-bottom: 32px' ),
				'note'     => 'The design opens the home page with the monogram, 40px, and 32px of air under '
					. 'it. The theme drew nothing there. ADR-0011 already settles that the mark is content, so '
					. 'this is a `core/site-logo` in the template and a box in the stylesheet.',
			),
			array(
				'id'       => 'home.hero.title',
				'sweep'    => 'home',
				'selector' => 'h1.dp-home-hero-title',
				'file'     => $home,
				'xpath'    => self::styled( 'margin: 0; font-family: var(--font-display); font-weight: 700; font-size: var(--fs-display); line-height: var(--lh-tight); letter-spacing: var(--ls-display); text-wrap: balance' ),
			),
			array(
				'id'           => 'home.hero.accent',
				'sweep'        => 'home',
				'selector'     => 'h1.dp-home-hero-title .dp-accent',
				'file'         => $home,
				'anchor'       => 'HERO_ACCENTS[heroAccent], with the design\'s own default of "teal"',
				'declarations' => array( 'color' => $this->logic->constant( $home, 'HERO_ACCENTS', 'teal' ) ),
			),
			array(
				'id'       => 'home.hero.lead',
				'sweep'    => 'home',
				'selector' => 'p.dp-home-hero-lead',
				'file'     => $home,
				'xpath'    => self::styled( 'margin: 40px 0 0; max-width: var(--measure); font-size: var(--fs-lg); line-height: var(--lh-relaxed); color: var(--text-primary); text-wrap: pretty' ),
			),
			array(
				'id'       => 'home.hero.note',
				'sweep'    => 'home',
				'selector' => 'p.dp-home-hero-note',
				'file'     => $home,
				'xpath'    => self::styled( 'margin: 24px 0 0; max-width: var(--measure); font-size: var(--fs-md); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),
			array(
				'id'       => 'home.hero.actions',
				'sweep'    => 'home',
				'selector' => '.dp-home-hero-actions',
				'file'     => $home,
				'xpath'    => self::styled( 'display: flex; flex-wrap: wrap; gap: 12px; margin-top: 40px' ),
			),

			/* Right now — the bento, and the strip of past roles under it. */
			array(
				'id'       => 'home.now',
				'sweep'    => 'home',
				'selector' => 'section.dp-right-now',
				'file'     => $home,
				'xpath'    => self::styled( $homenow ),
				'skip'     => $centred,
			),
			array(
				'id'       => 'home.now.head',
				'sweep'    => 'home',
				'selector' => '.dp-right-now .dp-section-head',
				'file'     => $head,
				'xpath'    => '(//div)[1]',
			),
			array(
				'id'       => 'home.now.head.kicker',
				'sweep'    => 'home',
				'selector' => '.dp-right-now p.dp-section-head-kicker',
				'file'     => $head,
				'xpath'    => self::styled( 'font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-caps); color: {{ toneColor }}' ),
				'override' => array( 'color' => $this->logic->constant( 'components/SectionHead.logic.js', 'TONES', 'teal' ) ),
				'skip'     => array(
					'textTransform' => 'The label is a translated string; the theme casts the case in CSS.',
				),
				'note'     => 'The kicker\'s colour is a template hole. The home view calls SectionHead with '
					. 'tone="teal", and TONES is a constant in the component\'s own script block, so the value '
					. 'is read from there rather than copied.',
			),
			array(
				'id'       => 'home.now.head.meta',
				'sweep'    => 'home',
				'selector' => '.dp-right-now p.dp-section-head-meta',
				'file'     => $head,
				'xpath'    => self::styled( $mono . '; text-wrap: balance' ),
				'note'     => 'RIGHT NOW is called with a meta and no action, so the meta renders. THE RECORD '
					. 'below it is called with an action and no meta, and `hasMeta: !!meta && !action` means '
					. 'the design would suppress a meta there even if one were passed.',
			),
			array(
				'id'       => 'home.bento',
				'sweep'    => 'home',
				'selector' => '.dp-bento',
				'logic'    => array(
					'file' => $home,
					'name' => 'bentoStyle',
					'env'  => $wide,
				),
				'skip'     => array(
					'gridTemplateColumns' => 'Six equal tracks either way; the two sides differ in the sixteenth '
						. 'of a pixel each one rounds to, because the probe has no items in it and the real grid '
						. 'has five. The rule is identical in both, and the rule is the value.',
				),
			),
			array(
				'id'       => 'home.tile',
				'sweep'    => 'home',
				'selector' => '.dp-bento > .dp-tile:not(.dp-tile-wide):not(.dp-tile-cloud):not(.dp-tile-aside)',
				'logic'    => array(
					'file' => $home,
					'name' => 'tileKiveo',
					'env'  => $wide,
				),
			),
			array(
				'id'       => 'home.tile.wide',
				'sweep'    => 'home',
				'selector' => '.dp-bento > .dp-tile-wide',
				'logic'    => array(
					'file' => $home,
					'name' => 'tileLab',
					'env'  => $wide,
				),
			),
			array(
				'id'       => 'home.tile.cloud',
				'sweep'    => 'home',
				'selector' => '.dp-bento > .dp-tile-cloud',
				'logic'    => array(
					'file' => $home,
					'name' => 'tileCloud',
					'env'  => $wide,
				),
			),
			array(
				'id'       => 'home.tile.aside',
				'sweep'    => 'home',
				'selector' => '.dp-bento > .dp-tile-aside',
				'logic'    => array(
					'file' => $home,
					'name' => 'tileOff',
					'env'  => $wide,
				),
			),
			array(
				'id'       => 'home.record',
				'sweep'    => 'home',
				'selector' => '.dp-record',
				'logic'    => array(
					'file' => $home,
					'name' => 'recordGridStyle',
					'env'  => array( 'recordCols' => 3 ),
				),
				'skip'     => array(
					'gridTemplateColumns' => 'The design draws the strip as a `<div>` and the theme as a `<ul>`, '
						. 'because it is a list of roles. The probe is the same tag as its target, so it takes '
						. "the user agent's 40px list indent, which `.dp-record` zeroes — and three equal tracks "
						. 'of a 1016px box are not three equal tracks of a 1056px one. The track rule is '
						. 'identical in both; that it produces three equal columns is asserted on the rendered '
						. 'box in a test of its own, the way the chips\' target size is.',
				),
				'note'     => 'Three fixed columns, not `auto-fit`. The design says why in a comment: "6 record '
					. 'cells: 3 / 2 / 1 all divide evenly, so no cell is ever orphaned on its own row", and its '
					. 'divider rule follows the column position rather than the array index.',
			),
			array(
				'id'       => 'home.record.cell',
				'sweep'    => 'home',
				'selector' => '.dp-record > li',
				'logic'    => array(
					'file' => $home,
					'name' => 'cellStyle',
					'env'  => array(
						'i'          => 0,
						'a'          => array(),
						'recordCols' => 3,
					),
					'only' => array( 'padding-right' ),
				),
				'note'     => 'The divider is `border-right` on every cell except the last of a row and the last '
					. 'overall, which is arithmetic on the cell index and so is a rule rather than a value; the '
					. 'theme states it as `:nth-child(3n)` and `:last-child`. What is pinned here is the gutter.',
			),
			array(
				'id'       => 'home.record.org',
				'sweep'    => 'home',
				'selector' => 'h3.dp-record-org',
				'logic'    => array(
					'file' => $home,
					'name' => 'orgStyle',
					'env'  => array(),
				),
			),
			array(
				'id'       => 'home.record.role',
				'sweep'    => 'home',
				'selector' => '.dp-record-role',
				'logic'    => array(
					'file' => $home,
					'name' => 'roleStyle',
					'env'  => array( 'r' => array( 'org' => 'MonsterInsights' ) ),
				),
				'skip'     => array(
					'textTransform' => 'The role title is a field David types; the theme casts the case in CSS.',
				),
				'note'     => 'Bound to a role that is not the current one, because the design paints the '
					. 'current one — `r.org === \'Fanxie Lab\'` — in `--hue-pink`. The theme draws every role '
					. 'muted; see the merge queue.',
			),
			array(
				'id'       => 'home.record.years',
				'sweep'    => 'home',
				'selector' => '.dp-record-years',
				'file'     => $home,
				'xpath'    => self::styled( $mono . '; margin-top: 4px' ),
				'skip'     => array( 'textTransform' => 'See home.record.role.' ),
			),

			/* Things I have shipped. */
			array(
				'id'       => 'home.shipped',
				'sweep'    => 'home',
				'selector' => 'section.dp-band-closed',
				'file'     => $home,
				'xpath'    => self::styled_around( $closedband, $shippedh2 ),
			),
			array(
				'id'       => 'home.shipped.column',
				'sweep'    => 'home',
				'selector' => '.dp-band-closed > .dp-section',
				'file'     => $home,
				'xpath'    => self::styled_around( $column, $shippedh2 ),
				'skip'     => $centred,
			),
			array(
				'id'       => 'home.shipped.title',
				'sweep'    => 'home',
				'selector' => '.dp-shipped h2',
				'file'     => $home,
				'xpath'    => self::styled( $shippedh2 ),
			),
			array(
				'id'       => 'home.shipped.lede',
				'sweep'    => 'home',
				'selector' => '.dp-shipped > p',
				'file'     => $home,
				'xpath'    => self::styled( 'margin: 0 0 48px; max-width: var(--measure); font-size: var(--fs-md); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),
			array(
				'id'       => 'home.shipped.item',
				'sweep'    => 'home',
				'selector' => '.dp-shipped-item',
				'file'     => $home,
				'xpath'    => self::styled( 'padding: 32px 0; border-top: 1px solid var(--border-subtle)' ),
			),
			array(
				'id'       => 'home.shipped.badges',
				'sweep'    => 'home',
				'selector' => '.dp-shipped-item .dp-badges',
				'file'     => $home,
				'xpath'    => self::styled_within( $closedband, 'display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 16px' ),
			),
			array(
				'id'       => 'home.shipped.item.title',
				'sweep'    => 'home',
				'selector' => '.dp-shipped-item h3',
				'file'     => $home,
				'xpath'    => self::styled( 'margin: 0 0 16px; font-family: var(--font-display); font-size: var(--fs-xl); line-height: var(--lh-snug); letter-spacing: var(--ls-display)' ),
				'note'     => 'The design draws the first of the three at `--fs-xl` and the other two at '
					. '`--fs-lg`. Nothing in the design says why, and the theme cannot express "the first one '
					. 'is bigger" as a rule about content David owns, so all three are `--fs-xl` and the '
					. 'question is in the merge queue.',
			),
			array(
				'id'       => 'home.shipped.item.body',
				'sweep'    => 'home',
				'selector' => '.dp-shipped-item p:not(.dp-label):not(.dp-badge)',
				'file'     => $home,
				'xpath'    => self::styled_within( $closedband, 'margin: 0 0 16px; max-width: var(--measure); font-size: var(--fs-base); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),
			array(
				'id'       => 'home.shipped.item.stack',
				'sweep'    => 'home',
				'selector' => '.dp-shipped-item .dp-label',
				'file'     => $home,
				'xpath'    => self::styled_within( $closedband, $mono ),
				'skip'     => array( 'textTransform' => 'See home.record.role.' ),
			),

			/* Latest writing. */
			array(
				'id'       => 'home.latest',
				'sweep'    => 'home',
				'selector' => 'section.dp-band:not(.dp-band-closed)',
				'file'     => $home,
				'xpath'    => self::styled_around( $openband, $latesthead ),
				'note'     => 'One border, not two: the band that closes the record is fenced top and bottom, '
					. 'and the one that opens the writing is fenced only at the top.',
			),
			array(
				'id'       => 'home.latest.head',
				'sweep'    => 'home',
				'selector' => '.dp-latest',
				'file'     => $home,
				'xpath'    => self::styled( $latesthead ),
			),
			array(
				'id'       => 'home.latest.title',
				'sweep'    => 'home',
				'selector' => '.dp-latest h2',
				'file'     => $home,
				'xpath'    => self::styled( 'margin: 0; font-family: var(--font-display); font-weight: 700; font-size: clamp(2rem, 4.5vw, 3rem); line-height: var(--lh-tight); letter-spacing: var(--ls-display)' ),
			),
			array(
				'id'       => 'home.latest.action',
				'sweep'    => 'home',
				'selector' => '.dp-latest .wp-block-button__link',
				'file'     => $home,
				'xpath'    => self::styled( 'cursor: pointer; font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-caps); color: var(--accent-text)' ),
				'skip'     => array( 'textTransform' => 'See home.record.role.' ),
			),
		);
	}
}
