<?php
/**
 * Generator for the work template's design-parity baseline.
 *
 * @package DP\Tests
 */

declare( strict_types=1 );

namespace DP\Tests\Support;

use RuntimeException;

/**
 * Builds `tests/e2e/fixtures/work-design-baseline.json` from `design-source/`.
 *
 * The map below is the only hand-written part, and it is deliberately the only
 * hand-written part. Mapping a design element to a theme element is a judgement
 * about *role* — the design's "kind label" is the theme's `.dp-tl-kind` — and no
 * generator can make it. Everything to the right of that judgement is read out
 * of the design source: the anchor names one element of one `.dc.html`, and the
 * declarations come back exactly as the design wrote them, `var()` names intact.
 *
 * Three consequences, all of them the point:
 *
 * **No value in the fixture was chosen by this theme.** If a number is pinned,
 * `design-source/` said it. If the design does not say it, it is not pinned, and
 * where the theme had to supply something anyway the entry carries a `skip` with
 * the reason. See `docs/adr/0012-design-parity-harness.md`.
 *
 * **An anchor that stops matching is a failure, not a silent gap.** The design
 * moves by re-import, and `composer design:check` fails the moment an element it
 * names has changed shape, which is the signal to re-read the component.
 *
 * **Values stay unevaluated.** `var(--fs-xs)` is written to the fixture as
 * `var(--fs-xs)`, and `tests/e2e/design-parity.spec.ts` hands it to the browser
 * to resolve. That is what makes `ch`, `em`, `clamp()` of a viewport unit and
 * `color-mix()` assertable at all: both sides are resolved by one engine, in one
 * font context, at one viewport, instead of being re-implemented in PHP and
 * compared to a number that would rot.
 */
final class DesignBaseline {

	/**
	 * Path of the generated fixture, relative to the repository root.
	 */
	public const OUTPUT = 'tests/e2e/fixtures/work-design-baseline.json';

	/**
	 * The two widths the baseline is measured at.
	 *
	 * `desktop` is wide enough that every `clamp()` on the page has reached its
	 * ceiling and the chart's container query is in bars mode. `narrow` is inside
	 * the design's own 700px breakpoint, so it is the stack mode.
	 */
	private const VIEWPORTS = array(
		'desktop' => 1600,
		'narrow'  => 520,
	);

	/**
	 * Constructor.
	 *
	 * @param DesignMarkup $markup The design's component files.
	 */
	public function __construct( private readonly DesignMarkup $markup ) {}

	/**
	 * Build a baseline for the repository at `$root`.
	 *
	 * @param string $root Absolute path to the repository root.
	 * @return self
	 */
	public static function for_repository( string $root ): self {
		return new self( DesignMarkup::from_repository( $root ) );
	}

	/**
	 * Render the fixture.
	 *
	 * @return string JSON, newline-terminated.
	 *
	 * @throws RuntimeException If the JSON cannot be encoded.
	 */
	public function render(): string {
		$entries = array();

		foreach ( $this->map() as $definition ) {
			$entries[] = $this->entry( $definition );
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.json_encode_json_encode -- the generator runs from the command line, before WordPress exists.
		$json = json_encode(
			array(
				'$comment'  => 'Generated by `composer design:baseline` from design-source/. Never hand-edited; '
					. 'see tests/Support/DesignBaseline.php and docs/adr/0012-design-parity-harness.md.',
				'viewports' => self::VIEWPORTS,
				'entries'   => $entries,
			),
			JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
		);

		if ( ! is_string( $json ) ) {
			throw new RuntimeException( 'The design baseline could not be encoded as JSON.' );
		}

		return $json . "\n";
	}

	/**
	 * Resolve one map definition into a fixture entry.
	 *
	 * @param array<string, mixed> $definition One row of the map.
	 * @return array<string, mixed>
	 *
	 * @throws RuntimeException If the definition is malformed.
	 */
	private function entry( array $definition ): array {
		$file  = self::text( $definition, 'file' );
		$xpath = isset( $definition['xpath'] ) ? self::text( $definition, 'xpath' ) : '';

		if ( '' === $xpath ) {
			/*
			 * A prose entry. `TimelineChart.dc.html` closes with a block of
			 * LAYOUT NOTES that gives numbers the inline styles cannot, because
			 * the styles they belong to are computed in the design tool and
			 * never reach the exported file. The note is the design saying it in
			 * words, so it is quoted here rather than invented.
			 */
			$declarations = self::declarations( $definition, 'declarations' );
			$anchor       = self::text( $definition, 'anchor' );
		} else {
			$declarations = $this->markup->declarations( $file, $xpath );
			$anchor       = $xpath;
		}

		foreach ( self::declarations( $definition, 'override' ) as $property => $value ) {
			$declarations[ $property ] = $value;
		}

		/*
		 * The design's own document sets `font-family` and `color` on `body` and
		 * nothing else — no line-height anywhere above a component
		 * (dpaternina.dc.html, the `<style>` block in its helmet). So an element
		 * the design gives a size and no leading is drawn in the browser's
		 * `normal` line box, and that absence is a value: `theme.json` has a root
		 * `--lh-relaxed`, which is 1.65 where the design renders about 1.2, and
		 * an element that inherits it is four pixels taller than the design draws
		 * per label. Deriving it here rather than leaving the property
		 * unasserted is what stops the harness repeating `spacing.spec.ts`'s
		 * mistake in a new form: a property the design declines to set is
		 * exactly the kind a page-versus-page test can never see.
		 */
		if ( isset( $declarations['font-size'] ) && ! isset( $declarations['line-height'] ) ) {
			$declarations['line-height'] = 'normal';
			$derived                     = array(
				'line-height' => 'Not written in the style attribute. The design declares a size here and no '
					. 'leading, and nothing above it declares one either, so this is the line box the design '
					. 'renders. See the note in tests/Support/DesignBaseline.php.',
			);
		}

		if ( array() === $declarations ) {
			throw new RuntimeException( sprintf( '%s: the anchor for "%s" yielded no declarations.', $file, self::text( $definition, 'id' ) ) );
		}

		$entry = array(
			'id'           => self::text( $definition, 'id' ),
			'viewport'     => self::text( $definition, 'viewport' ),
			'selector'     => self::text( $definition, 'selector' ),
			'source'       => array(
				'file'   => $file,
				'anchor' => $anchor,
			),
			'declarations' => $declarations,
		);

		if ( isset( $derived ) ) {
			$entry['derived'] = $derived;
		}

		$skip = self::declarations( $definition, 'skip' );

		if ( array() !== $skip ) {
			$entry['skip'] = $skip;
		}

		if ( isset( $definition['note'] ) ) {
			$entry['note'] = self::text( $definition, 'note' );
		}

		return $entry;
	}

	/**
	 * Read a required string out of a map definition.
	 *
	 * @param array<string, mixed> $definition One row of the map.
	 * @param string               $key        Which field.
	 * @return string
	 *
	 * @throws RuntimeException If the field is absent or not a string.
	 */
	private static function text( array $definition, string $key ): string {
		$value = $definition[ $key ] ?? null;

		if ( ! is_string( $value ) ) {
			throw new RuntimeException( sprintf( 'The design baseline map is missing a string "%s".', $key ) );
		}

		return $value;
	}

	/**
	 * Read an optional string-to-string field out of a map definition.
	 *
	 * @param array<string, mixed> $definition One row of the map.
	 * @param string               $key        Which field.
	 * @return array<string, string>
	 */
	private static function declarations( array $definition, string $key ): array {
		$value = $definition[ $key ] ?? array();

		if ( ! is_array( $value ) ) {
			return array();
		}

		$pairs = array();

		foreach ( $value as $property => $declared ) {
			if ( is_string( $property ) && is_string( $declared ) ) {
				$pairs[ $property ] = $declared;
			}
		}

		return $pairs;
	}

	/**
	 * An XPath expression selecting the one element carrying an exact style.
	 *
	 * Exact rather than `contains()`, because several of the design's labels are
	 * prefixes of each other — the year axis's span is the role's range span
	 * without its `margin-top` — and a prefix match would silently pick whichever
	 * came first.
	 *
	 * @param string $style   The complete `style` attribute value.
	 * @param int    $ordinal Which match, when the design repeats one declaration.
	 * @return string
	 */
	private static function styled( string $style, int $ordinal = 1 ): string {
		return sprintf( '(//*[@style="%s"])[%d]', $style, $ordinal );
	}

	/**
	 * An XPath expression selecting a styled element inside a styled ancestor.
	 *
	 * @param string $ancestor The ancestor's complete `style` attribute value.
	 * @param string $style    The target's complete `style` attribute value.
	 * @return string
	 */
	private static function styled_within( string $ancestor, string $style ): string {
		return sprintf( '(//*[@style="%s"]//*[@style="%s"])[1]', $ancestor, $style );
	}

	/**
	 * Every element of the work template, by role.
	 *
	 * Ordered the way the page is: the hero, the featured cards, the record's
	 * head and lede, the chart's shell, a closed row, an open role, an open
	 * shipped thing, the outro, the closing band.
	 *
	 * @return list<array<string, mixed>>
	 */
	private function map(): array {
		$hero     = 'components/PageHero.dc.html';
		$head     = 'components/SectionHead.dc.html';
		$card     = 'components/WorkCard.dc.html';
		$pills    = 'components/FilterPills.dc.html';
		$chart    = 'components/TimelineChart.dc.html';
		$view     = 'dpaternina.dc.html';
		$featured = 'max-width: var(--container-lg); margin: 0 auto; padding: 24px var(--gutter) 64px';
		$record   = 'max-width: var(--container-lg); margin: 0 auto; padding: 20px var(--gutter) 120px';
		$outro    = 'display: flex; flex-wrap: wrap; align-items: baseline; justify-content: space-between; gap: 16px 24px; margin-top: 40px; padding-top: 24px; border-top: 1px solid var(--border-subtle)';
		$band     = 'max-width: var(--container-lg); margin: 0 auto; padding: clamp(96px, 14vw, 160px) var(--gutter) clamp(104px, 15vw, 168px); text-align: center';
		$mono     = 'font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-caps); color: var(--text-muted)';
		$gold     = 'font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-caps); color: var(--hue-gold)';
		$factlbl  = 'font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-caps); color: var(--text-muted); margin-bottom: 4px';
		$range    = 'font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-wide); color: var(--text-muted); margin-top: 4px';
		$tile     = 'flex: 1 1 140px; padding: 16px; border-radius: var(--radius-sm); background: var(--bg-page); border: 1px solid var(--border-subtle)';

		$centred = array(
			'marginLeft'  => 'The design centres this column with `margin: 0 auto`. `auto` computes to a used '
				. 'value that depends on the free space beside it, so what is asserted is the `max-width` '
				. 'that creates the column and the `text-align` inside it, not the two numbers that fall out.',
			'marginRight' => 'See marginLeft.',
		);

		return array(
			/* ---- The hero ---------------------------------------------- */
			array(
				'id'           => 'hero.section',
				'viewport'     => 'desktop',
				'selector'     => '.dp-hero',
				'file'         => $hero,
				'anchor'       => 'the trailing note: wrapStyle',
				'declarations' => array(
					'max-width' => 'var(--container-lg)',
					'margin'    => '0 auto',
					'padding'   => 'clamp(48px, 8vw, 80px) var(--gutter) 40px',
				),
				'skip'         => $centred,
				'note'         => 'PageHero computes wrapStyle in the design tool, so the numbers come from the '
					. "component's own closing note, for width 'lg' and tight = false, which is how the work "
					. 'view calls it.',
			),
			array(
				'id'       => 'hero.title',
				'viewport' => 'desktop',
				'selector' => 'h1.dp-hero-title',
				'file'     => $hero,
				'xpath'    => '(//h1)[1]',
				'override' => array( 'max-width' => '20ch' ),
				'note'     => 'max-width is a template hole; the work view fills it with title-max="20ch" '
					. '(dpaternina.dc.html, the isTimeline PageHero call).',
			),
			array(
				'id'       => 'hero.deck',
				'viewport' => 'desktop',
				'selector' => 'p.dp-hero-deck',
				'file'     => $hero,
				'xpath'    => self::styled( 'margin: 0; max-width: var(--measure); font-size: var(--fs-md); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),

			/* ---- Featured work ----------------------------------------- */
			array(
				'id'       => 'featured.section',
				'viewport' => 'desktop',
				'selector' => 'section.dp-work-featured',
				'file'     => $view,
				'xpath'    => self::styled( $featured ),
				'skip'     => $centred,
			),
			array(
				'id'       => 'featured.head.wrapper',
				'viewport' => 'desktop',
				'selector' => '.dp-work-featured .dp-section-head',
				'file'     => $view,
				'xpath'    => self::styled_within( $featured, 'margin-bottom: 32px' ),
				'note'     => 'The design puts the gap under the head on a wrapper around it; the theme puts it '
					. 'on the head itself, which is the same value on the same edge with one element fewer.',
			),
			array(
				'id'       => 'featured.head',
				'viewport' => 'desktop',
				'selector' => '.dp-work-featured .dp-section-head',
				'file'     => $head,
				'xpath'    => '(//div)[1]',
			),
			array(
				'id'       => 'featured.head.heading',
				'viewport' => 'desktop',
				'selector' => 'h2.dp-section-head-heading',
				'file'     => $head,
				'xpath'    => '(//h2)[1]',
			),
			array(
				'id'       => 'featured.head.meta',
				'viewport' => 'desktop',
				'selector' => '.dp-work-featured p.dp-section-head-meta',
				'file'     => $head,
				'xpath'    => self::styled( $mono . '; text-wrap: balance' ),
			),
			array(
				'id'       => 'featured.grid',
				'viewport' => 'desktop',
				'selector' => 'ul.dp-cards',
				'file'     => $view,
				'xpath'    => self::styled_within( $featured, 'display: grid; grid-template-columns: repeat(auto-fit, minmax(min(280px, 100%), 1fr)); gap: 20px' ),
				'skip'     => array(
					'gridTemplateColumns' => '`auto-fit` collapses the tracks it has no items for, and the '
						. 'probe beside the grid is empty, so the two sides are not measuring the same '
						. 'question. The track *rule* is what matters and it is identical in both '
						. 'stylesheets; what it produces is a function of how many cards David has '
						. 'marked featured, which is content.',
				),
			),
			array(
				'id'       => 'card',
				'viewport' => 'desktop',
				'selector' => '.dp-card',
				'file'     => $card,
				'xpath'    => '(//div)[1]',
				'skip'     => array(
					'cursor' => 'The design makes the whole card the control. The theme makes the title the '
						. 'link and covers the card with its `::after`, which is one tab stop instead of a '
						. "card's worth and the same target for a mouse. Delivery mechanism, not value.",
					'height' => 'A grid item stretching to its row is a used value, and the probe beside it is '
						. 'empty. `height: 100%` is asserted by the row heights being equal, which the grid '
						. 'gives for free.',
				),
			),
			array(
				'id'       => 'card.body',
				'viewport' => 'desktop',
				'selector' => '.dp-card-body',
				'file'     => $card,
				'xpath'    => self::styled( 'padding: 24px; display: flex; flex-direction: column; gap: 10px; flex: 1' ),
			),
			array(
				'id'       => 'card.meta',
				'viewport' => 'desktop',
				'selector' => '.dp-card-meta',
				'file'     => $card,
				'xpath'    => self::styled( 'display: flex; flex-wrap: wrap; gap: 4px 12px; ' . $mono ),
			),
			array(
				'id'       => 'card.year',
				'viewport' => 'desktop',
				'selector' => 'p.dp-card-year',
				'file'     => $card,
				'xpath'    => self::styled( 'color: var(--hue-gold)' ),
			),
			array(
				'id'       => 'card.title',
				'viewport' => 'desktop',
				'selector' => 'h3.dp-card-title',
				'file'     => $card,
				'xpath'    => '(//h3)[1]',
			),
			array(
				'id'       => 'card.line',
				'viewport' => 'desktop',
				'selector' => 'p.dp-card-line',
				'file'     => $card,
				'xpath'    => self::styled( 'margin: 0; flex: 1; font-size: var(--fs-sm); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),

			/* ---- The whole record -------------------------------------- */
			array(
				'id'       => 'record.section',
				'viewport' => 'desktop',
				'selector' => 'section.dp-work-record',
				'file'     => $view,
				'xpath'    => self::styled( $record ),
				'skip'     => $centred,
			),
			array(
				'id'       => 'record.head.wrapper',
				'viewport' => 'desktop',
				'selector' => '.dp-work-record .dp-section-head',
				'file'     => $view,
				'xpath'    => self::styled_within( $record, 'margin-bottom: 24px' ),
			),
			array(
				'id'       => 'record.head.meta',
				'viewport' => 'desktop',
				'selector' => '.dp-work-record p.dp-section-head-meta',
				'file'     => $head,
				'xpath'    => self::styled( $mono . '; text-wrap: balance' ),
			),
			array(
				'id'       => 'record.lede',
				'viewport' => 'desktop',
				'selector' => 'p.dp-work-lede',
				'file'     => $view,
				'xpath'    => self::styled( 'margin: 0 0 24px; max-width: var(--measure); font-size: var(--fs-base); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),

			/* ---- The chart's shell ------------------------------------- */
			array(
				'id'       => 'chart.pills',
				'viewport' => 'desktop',
				'selector' => 'ul.dp-filter-pills.dp-tl-pills',
				'file'     => $pills,
				'xpath'    => self::styled( 'display: flex; gap: 8px; flex-wrap: wrap; align-items: center' ),
			),
			array(
				'id'       => 'chart.pills.gap-below',
				'viewport' => 'desktop',
				'selector' => 'ul.dp-filter-pills.dp-tl-pills',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; gap: 8px; margin-bottom: 28px; flex-wrap: wrap; align-items: center' ),
				'note'     => 'The chart wraps FilterPills in a row of its own to carry the 28px below it; the '
					. 'theme puts that margin on the list, which is the same edge without the wrapper.',
			),
			array(
				'id'       => 'chart.pill',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-pill-extra a',
				'file'     => $pills,
				'xpath'    => self::styled( 'cursor: pointer; min-height: var(--target-min); padding: 8px 20px; border-radius: var(--radius-pill); border: 1px dashed var(--border-subtle); background: transparent; ' . $mono . '; transition: color var(--dur-base) var(--ease-standard), border-color var(--dur-base) var(--ease-standard)' ),
				'note'     => "The design's expand-all control carries the pill's whole box on an inline style, "
					. 'which is why it is the anchor for a shape the other three pills describe only in prose.',
			),
			array(
				'id'           => 'chart.card',
				'viewport'     => 'desktop',
				'selector'     => '.dp-tl-card',
				'file'         => $chart,
				'anchor'       => 'the closing LAYOUT NOTES: "Card: padding clamp(20px,3vw,32px) (bars) … radius lg, bg var(--bg-surface), 1px var(--border-subtle)"',
				'declarations' => array(
					'padding'       => 'clamp(20px, 3vw, 32px)',
					'border-radius' => 'var(--radius-lg)',
					'background'    => 'var(--bg-surface)',
					'border'        => '1px solid var(--border-subtle)',
				),
			),
			array(
				'id'           => 'chart.card.stack',
				'viewport'     => 'narrow',
				'selector'     => '.dp-tl-card',
				'file'         => $chart,
				'anchor'       => 'the closing LAYOUT NOTES: "Card: padding … / 4px 16px 24px (stack)"',
				'declarations' => array( 'padding' => '4px 16px 24px' ),
			),
			array(
				'id'       => 'chart.legend.swatch.role',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-swatch-role',
				'file'     => $chart,
				'xpath'    => self::styled( 'width: 8px; height: 8px; border-radius: var(--radius-xs); background: var(--dp-teal); flex: none' ),
			),
			array(
				'id'       => 'chart.legend.swatch.ship',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-swatch-ship',
				'file'     => $chart,
				'xpath'    => self::styled( 'width: 16px; height: 8px; border-radius: var(--radius-xs); background: var(--dp-gold); flex: none' ),
			),
			array(
				'id'       => 'chart.legend.key',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-key',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: inline-flex; align-items: center; gap: 8px' ),
			),
			array(
				'id'       => 'chart.years',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-years',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; justify-content: space-between' ),
			),
			array(
				'id'       => 'chart.years.label',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-years span',
				'file'     => $chart,
				'xpath'    => self::styled( 'font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-wide); color: var(--text-muted)' ),
			),
			array(
				'id'       => 'chart.lanes',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-lanes',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; flex-direction: column; gap: 8px; padding-top: 18px' ),
			),
			array(
				'id'       => 'chart.swipe',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-swipe',
				'file'     => $chart,
				'xpath'    => self::styled( 'padding-top: 14px; margin-top: 4px; border-top: 1px solid var(--border-subtle); ' . $mono ),
				'note'     => 'Drawn only in scroll mode, which is the variant rather than the default; the '
					. 'element is in the document either way, so its box is comparable at any width.',
			),

			/* ---- A row, and the role behind it ------------------------- */
			array(
				'id'       => 'row.role.title',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-row-role .dp-tl-role',
				'file'     => $chart,
				'xpath'    => self::styled( 'font-size: var(--fs-xs); color: var(--text-muted)' ),
			),
			array(
				'id'       => 'row.range',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-row-role .dp-tl-range',
				'file'     => $chart,
				'xpath'    => self::styled( $range ),
			),
			array(
				'id'       => 'row.role.track',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-row-role .dp-tl-track',
				'file'     => $chart,
				'xpath'    => self::styled( 'position: relative; height: 40px; border-radius: var(--radius-sm); background: color-mix(in srgb, var(--text-primary) 3%, transparent)' ),
			),
			array(
				'id'       => 'row.ship.track',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-row-ship .dp-tl-track',
				'file'     => $chart,
				'xpath'    => self::styled( 'position: relative; height: 32px; border-radius: var(--radius-xs); background: color-mix(in srgb, var(--text-primary) 2%, transparent)' ),
			),
			array(
				'id'           => 'row.role.open',
				'viewport'     => 'desktop',
				'selector'     => '.dp-tl-row-role[open]',
				'file'         => $chart,
				'anchor'       => 'the closing LAYOUT NOTES: "Open rows tint with color-mix(in srgb, var(--dp-white) 4%, transparent) … and bleed … -16px (bars) into the card padding"',
				'declarations' => array(
					'background'     => 'color-mix(in srgb, var(--dp-white) 4%, transparent)',
					'margin-inline'  => '-16px',
					'padding-inline' => '16px',
				),
			),
			array(
				'id'           => 'row.role.open.stack',
				'viewport'     => 'narrow',
				'selector'     => '.dp-tl-row-role[open]',
				'file'         => $chart,
				'anchor'       => 'the closing LAYOUT NOTES: "… bleed -12px (stack)"',
				'declarations' => array(
					'margin-inline'  => '-12px',
					'padding-inline' => '12px',
				),
			),
			array(
				'id'           => 'row.ship.open',
				'viewport'     => 'desktop',
				'selector'     => '.dp-tl-row-ship[open]',
				'file'         => $chart,
				'anchor'       => 'the closing LAYOUT NOTES: "(2.5% for ships in bars mode)"',
				'declarations' => array( 'background' => 'color-mix(in srgb, var(--dp-white) 2.5%, transparent)' ),
			),
			array(
				'id'           => 'row.ships.rail',
				'viewport'     => 'desktop',
				'selector'     => '.dp-tl-ships',
				'file'         => $chart,
				'anchor'       => 'the closing LAYOUT NOTES: "shipsWrapStyle paddingLeft = 16 (stack) / 20 (bars)"',
				'declarations' => array( 'padding-left' => '20px' ),
			),
			array(
				'id'           => 'row.ships.rail.stack',
				'viewport'     => 'narrow',
				'selector'     => '.dp-tl-ships',
				'file'         => $chart,
				'anchor'       => 'the closing LAYOUT NOTES: "shipsWrapStyle paddingLeft = 16 (stack)"',
				'declarations' => array( 'padding-left' => '16px' ),
			),
			array(
				'id'       => 'row.detail.prose',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-row-role[open] p.dp-tl-prose',
				'file'     => $chart,
				'xpath'    => self::styled( 'margin: 0 0 12px; max-width: var(--measure); font-size: var(--fs-base); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),
			array(
				'id'       => 'row.detail.stack',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-stack',
				'file'     => $chart,
				'xpath'    => self::styled( $mono ),
				'skip'     => array(
					'textTransform' => 'The design prints the stack from a fixture that is already upper case; '
						. 'the theme takes it from a field David types, so the case is a rule rather than a '
						. 'habit. Same rendered text, and the letter-spacing that goes with caps is asserted.',
				),
			),

			/* ---- An open shipped thing --------------------------------- */
			array(
				'id'           => 'panel',
				'viewport'     => 'desktop',
				'selector'     => '.dp-tl-panel',
				'file'         => $chart,
				'anchor'       => 'the closing LAYOUT NOTES: "Expanded ship panel: background var(--band), 1px var(--border-subtle), radius sm"',
				'declarations' => array(
					'background'    => 'var(--band)',
					'border'        => '1px solid var(--border-subtle)',
					'border-radius' => 'var(--radius-sm)',
				),
			),
			array(
				'id'       => 'panel.main',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-panel-main',
				'file'     => $chart,
				'xpath'    => self::styled( 'flex: 1 1 320px; min-width: 0' ),
			),
			array(
				'id'       => 'panel.aside',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-panel-aside',
				'file'     => $chart,
				'xpath'    => self::styled( 'flex: 1 1 260px; min-width: 0; display: flex; flex-direction: column; gap: 12px' ),
			),
			array(
				'id'       => 'panel.shipped',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-shipped',
				'file'     => $chart,
				'xpath'    => self::styled( $gold . '; margin-bottom: 12px' ),
				'skip'     => array( 'textTransform' => 'See row.detail.stack: the theme upper-cases a field rather than a fixture.' ),
			),
			array(
				'id'       => 'panel.prose',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-panel p.dp-tl-prose',
				'file'     => $chart,
				'xpath'    => self::styled( 'margin: 0 0 16px; max-width: var(--measure); font-size: var(--fs-base); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
			),
			array(
				'id'       => 'panel.bullets',
				'viewport' => 'desktop',
				'selector' => 'ul.dp-tl-bullets',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; flex-direction: column; gap: 8px; margin-bottom: 20px' ),
			),
			array(
				'id'       => 'panel.bullet',
				'viewport' => 'desktop',
				'selector' => 'li.dp-tl-bullet',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; gap: 12px; align-items: baseline; font-size: var(--fs-sm); line-height: var(--lh-relaxed); color: var(--text-secondary)' ),
				'skip'     => array(
					'display' => 'The design hangs its em dash off a real `<span>`; the theme draws it with '
						. '`::before`, which needs a track to sit in. Grid rather than flex is the delivery '
						. 'mechanism (CLAUDE.md §5); the gap, the baseline and the type are the values.',
				),
			),
			array(
				'id'       => 'panel.facts',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-facts',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; flex-wrap: wrap; gap: 20px 24px; padding-top: 16px; border-top: 1px solid var(--border-subtle)' ),
			),
			array(
				'id'       => 'panel.fact.label',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-fact-label',
				'file'     => $chart,
				'xpath'    => self::styled( $factlbl ),
				'skip'     => array( 'textTransform' => 'The label is a translated string; the theme casts the case in CSS so a translation can carry lower-case letters.' ),
			),
			array(
				'id'       => 'panel.fact.value',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-fact-value',
				'file'     => $chart,
				'xpath'    => self::styled( 'font-size: var(--fs-sm)' ),
			),
			array(
				'id'       => 'panel.fact.stack',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-fact-stack',
				'file'     => $chart,
				'xpath'    => self::styled( $gold ),
				'skip'     => array( 'textTransform' => 'See row.detail.stack.' ),
			),
			array(
				'id'       => 'panel.writeup',
				'viewport' => 'desktop',
				'selector' => 'a.dp-tl-writeup',
				'file'     => $chart,
				'xpath'    => self::styled( 'cursor: pointer; font-size: var(--fs-sm); color: var(--accent-text)' ),
			),
			array(
				'id'       => 'panel.artifact',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-artifact',
				'file'     => $chart,
				'xpath'    => self::styled( 'border-radius: var(--radius-sm); background: var(--bg-page); border: 1px solid var(--border-subtle); overflow: hidden' ),
			),
			array(
				'id'       => 'panel.artifact.head',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-artifact-head',
				'file'     => $chart,
				'xpath'    => self::styled( 'padding: 12px 16px; border-bottom: 1px solid var(--border-subtle); display: flex; justify-content: space-between; align-items: center; gap: 12px; flex-wrap: wrap' ),
			),
			array(
				'id'       => 'panel.artifact.label',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-artifact-label',
				'file'     => $chart,
				'xpath'    => self::styled( $mono, 2 ),
			),
			array(
				'id'       => 'panel.artifact.tag',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-artifact-tag',
				'file'     => $chart,
				'xpath'    => self::styled( $gold, 2 ),
				'skip'     => array( 'textTransform' => 'The tag is a translated string; see panel.fact.label.' ),
			),
			array(
				'id'       => 'panel.artifact.body',
				'viewport' => 'desktop',
				'selector' => 'pre.dp-tl-artifact-body',
				'file'     => $chart,
				'xpath'    => self::styled( 'margin: 0; padding: 16px; font-family: var(--font-mono); font-size: var(--fs-xs); line-height: var(--lh-relaxed); color: var(--text-secondary); overflow-x: auto' ),
			),
			array(
				'id'       => 'panel.stats',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-stats',
				'file'     => $chart,
				'xpath'    => self::styled( 'display: flex; flex-wrap: wrap; gap: 12px' ),
			),
			array(
				'id'       => 'panel.stat',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-stat',
				'file'     => $chart,
				'xpath'    => self::styled( $tile ),
			),
			array(
				'id'       => 'panel.stat.loud',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-stat-loud .dp-tl-stat-value',
				'file'     => $chart,
				'xpath'    => self::styled( 'font-family: var(--font-display); font-size: var(--fs-lg); letter-spacing: var(--ls-display); color: var(--hue-gold)' ),
			),
			array(
				'id'       => 'panel.stat.quiet',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-stat-quiet .dp-tl-stat-value',
				'file'     => $chart,
				'xpath'    => self::styled( 'font-family: var(--font-display); font-size: var(--fs-lg); letter-spacing: var(--ls-display); color: var(--text-secondary)' ),
			),
			array(
				'id'       => 'panel.stat.label',
				'viewport' => 'desktop',
				'selector' => '.dp-tl-stat-label',
				'file'     => $chart,
				'xpath'    => self::styled( $mono . '; margin-top: 4px' ),
				'skip'     => array( 'textTransform' => 'See row.detail.stack.' ),
			),

			/* ---- The outro and the closing band ------------------------ */
			array(
				'id'       => 'outro',
				'viewport' => 'desktop',
				'selector' => '.dp-work-outro',
				'file'     => $view,
				'xpath'    => self::styled( $outro ),
			),
			array(
				'id'       => 'outro.line',
				'viewport' => 'desktop',
				'selector' => '.dp-work-outro p',
				'file'     => $view,
				'xpath'    => self::styled( 'margin: 0; max-width: var(--measure); font-size: var(--fs-base); line-height: var(--lh-relaxed); color: var(--text-secondary)' ),
			),
			array(
				'id'       => 'outro.action',
				'viewport' => 'desktop',
				'selector' => '.dp-work-outro .wp-block-button__link',
				'file'     => $view,
				'xpath'    => self::styled_within( $outro, 'cursor: pointer; white-space: nowrap; font-family: var(--font-mono); font-size: var(--fs-xs); letter-spacing: var(--ls-caps); color: var(--accent-text)' ),
				'skip'     => array( 'textTransform' => 'The label is a translated string; see panel.fact.label.' ),
			),
			array(
				'id'       => 'band',
				'viewport' => 'desktop',
				'selector' => 'section.dp-cta-band',
				'file'     => $view,
				'xpath'    => self::styled( $band ),
				'skip'     => array_merge(
					$centred,
					array(
						'maxWidth' => 'The design puts the glow on a full-bleed <section> and the column inside '
							. 'it. The theme has one element doing both, so the band cannot carry the column\'s '
							. 'max-width without cropping its own glow. Everything inside is centred or capped '
							. 'at --measure, so the only element the missing column would move is the heading, '
							. 'and it does not reach 1120px at any size. Recorded rather than closed: it is a '
							. 'real difference in shape.',
					)
				),
			),
			array(
				'id'       => 'band.title',
				'viewport' => 'desktop',
				'selector' => 'h2.dp-cta-band-title',
				'file'     => $view,
				'xpath'    => self::styled( 'margin: 0 0 16px; font-family: var(--font-display); font-weight: 700; font-size: clamp(2.25rem, 6vw, 3.75rem); line-height: var(--lh-tight); letter-spacing: var(--ls-display)' ),
			),
			array(
				'id'       => 'band.line',
				'viewport' => 'desktop',
				'selector' => 'p.dp-cta-band-line',
				'file'     => $view,
				'xpath'    => self::styled( 'margin: 0 auto 36px; max-width: var(--measure); font-size: var(--fs-base); line-height: var(--lh-relaxed); color: var(--text-secondary); text-wrap: pretty' ),
				'skip'     => $centred,
			),
			array(
				'id'       => 'band.buttons',
				'viewport' => 'desktop',
				'selector' => '.dp-cta-band .wp-block-buttons',
				'file'     => $view,
				'xpath'    => self::styled( 'display: flex; flex-wrap: wrap; gap: 12px; justify-content: center' ),
			),
		);
	}
}
